### ISSUE TITLE
Memory allocation error

### ISSUE THREAD

**Issue by mir07** [brndnmtthws/conky#106] opened 2015-07-03 18:07 UTC
Package: conky
Version: 1.10.0-1
Severity: important
Tags: upstream

When starting conky everything works but after running approximately 30 min conky crashes with the following output from DEBUG:
DEBUG(0) [/build/conky-FWDzxw/conky-1.10.0/src/specials.cc:460]: reallocing graph from 303 to 343
conky: malloc.c:3695: _int_malloc: Assertion `(unsigned long) (size) >= (unsigned long) (nb)' failed.

-- System Information:
Debian Release: stretch/sid
  APT prefers unstable
  APT policy: (900, 'unstable'), (1, 'experimental')
Architecture: amd64 (x86_64)
Foreign Architectures: i386

Kernel: Linux 4.0.0-2-amd64 (SMP w/6 CPU cores)
Locale: LANG=en_DK.UTF-8, LC_CTYPE=en_DK.UTF-8 (charmap=UTF-8)
Shell: /bin/sh linked to /bin/bash
Init: systemd (via /run/systemd/system)

Versions of packages conky depends on:
ii  conky-all  1.10.0-1

**Comment by corpix** [comment] 2015-07-05 23:54
Probably this could be a duplicate of https://github.com/brndnmtthws/conky/issues/103

**Comment by lasers** [comment] 2018-08-06 02:25
3 years 1 month passed. I found a duplicate behavior https://github.com/brndnmtthws/conky/issues/421#issuecomment-33774168 with newer date Oct 18, 2017.

_Using that instead..._

10 months passed. Too much has changed. We can track changes no more than with `git log -p 2600d013..HEAD --follow -- src/specials.cc`. That will give us three commits to work with.
```
... v1.10.7
* 3 months ago 4b92556f Brenden Matthews Build improvements: clang-tidy, sonar, Dockerfile. (#488)
* 3 months ago eebc8c65 Brenden Matthews Add formatting/static analysis (#486)
... v1.10.8
* 1 year, 6 months ago a58a6d4e Darin McBride Clean up a few valgrind errors, add realloc-failure handling for graphs. (#367)
```
The last commit looks unrelated now giving  us two commits to work with. We should only have to study few lines around `current->type = t;` and/or `reallocing graph from` to address `Assertion '(unsigned long) (size) >= (unsigned long) (nb)' failed.'`

**Comment by su8** [comment] 2018-08-06 15:28
I couldn't find any `'(unsigned long) (size) >= (unsigned long) (nb)'` traces in the current code. Otherwise `current->type = t;` is a **special type enum, e.g. alignc, alignr, fg, bg**

**Comment by lasers** [comment] 2018-08-06 15:35
Guy got it in `1.10.6`. Have you looked in that version? 4cd04f00 for `1.10.6` or e94f0494 for `1.10.5`. It looks like nothing changed between commits... Is only code smellz so it had to be somewhere. I dunno.

**Comment by lasers** [comment] 2018-08-07 10:41
@su8 No `malloc.c` here too. Keep this open or close?

**Comment by su8** [comment] 2018-08-07 10:54
Wait till mister Brenden releases a new conky version, so people can upgrade/migrate to the newer version.

**Comment by lasers** [comment] 2018-08-10 17:38
@su8 New version went out. Can we close this now?

**Comment by su8** [comment] 2018-08-10 17:47
Yes :octopus:

**Comment by lasers** [comment] 2018-08-10 17:51
Code no longer exist. Closing. :elephant:

**Closed by lasers** 2018-08-10 17:51 UTC
Labels: bug
