### ISSUE TITLE
Build fails with gcc7 due to missing include

### ISSUE THREAD

**Issue by oberon2007** [brndnmtthws/conky#396] opened 2017-05-29 00:59 UTC
**gcc7** is less tolerant with non-standard and deprecated code than **gcc6** was 😉 .
As a consequence conky can no longer be compiled.
There are various warnings about dynamic exception of the kind
```
/src/semaphore.hh:40:36: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
  semaphore(unsigned int value = 0) throw(std::logic_error)
```
and a lot of errors like
```
src/luamm.hh:39:15: error: ‘function’ in namespace ‘std’ does not name a template type
  typedef std::function<int(state *)> cpp_function;
```
or
```
src/luamm.hh:250:26: error: ‘cpp_function’ does not name a type; did you mean ‘lua_CFunction’?
   void pushclosure(const cpp_function &fn, int n);
```
full buildlog is [here](https://pastebin.com/u5saAbdY)

**Comment by oberon2007** [comment] 2017-05-30 22:46
In fact all the fatal errors result from **luamm.hh** file. The C/C++ - melange there doesn't seem to work out any longer ... 😜

**Comment by LoneFox78** [comment] 2017-06-01 05:13
The error is caused by a missing #include:

	diff -bur conky-1.10.6-orig/src/luamm.hh conky-1.10.6/src/luamm.hh
	--- conky-1.10.6-orig/src/luamm.hh      2016-12-04 17:13:57.000000000 +0200
	+++ conky-1.10.6/src/luamm.hh   2017-05-31 20:05:59.000000000 +0300
	@@ -28,6 +28,7 @@
	 #include <exception>
	 #include <stdexcept>
	 #include <string>
	+#include <functional>
	 
	 #include <lua.hpp>

**Comment by oberon2007** [comment] 2017-06-01 07:41
Awesome 😆 Thank you!

**Comment by easysid** [comment] 2018-01-14 16:09
This issue can now be closed as the patch is included in the repo

**Closed** 2018-01-14 16:40 UTC
