### ISSUE TITLE
cmake, make and make install passes but no lua/imlib2 support

### ISSUE THREAD

**Issue by c0debreaker** [brndnmtthws/conky#308] opened 2016-08-16 14:54 UTC
Here is the output of the latest conky -v

I followed your instructions. I installed all the necessary libraries you mentioned. However, I still don't see LUA support.

```
System config file: /etc/conky/conky.conf
Package library path: /usr/local/lib/conky
 
 
 General:
  * math
  * hddtemp
  * portmon
  * IPv6
  * support for IBM/Lenovo notebooks
  * builtin default configuration
  * old configuration syntax
  * apcupsd
  * iostats
  * ncurses
  * Internationalization support
 X11:
  * Xdamage extension
  * Xinerama extension (virtual display)
  * Xft
  * ARGB visual
  * Own window
 
 Music detection:
  * MPD
  * MOC
 
 Default values:
  * Netdevice: eth0
  * Local configfile: $HOME/.conkyrc
  * Localedir: /usr/local/share/locale
  * Maximum netdevices: 64
  * Maximum text size: 16384
  * Size text buffer: 256
```

**Comment by Nooby4Ever** [comment] 2016-08-16 15:08
Did you use any of the   `  -D BUILD_LUA_RSVG=ON  -D BUILD_LUA_CAIRO=ON   -D BUILD_LUA_IMLIB2=ON ` build flags? Since conky requires Lua (eg config files themselves) by default it is not explicitly mentioned in the overview unless you have used one of those flags.

In case your Lua scripts do not run, try at least adding the cairo build flag since many Lua scripts use cairo to draw.

**Comment by c0debreaker** [comment] 2016-08-16 15:12
I just ran cmake .. inside build directory

**Comment by c0debreaker** [comment] 2016-08-16 15:13
where do I put `-D BUILD_LUA_RSVG=ON -D BUILD_LUA_CAIRO=ON -D BUILD_LUA_IMLIB2=ON` and how do I check if cairo is installed on my debian?

**Comment by plikhari** [comment] 2016-08-16 15:13
What distro are you using ???

**Comment by c0debreaker** [comment] 2016-08-16 15:14
It's Bunselabs which is Debian 8.5 (Hydrogen)

**Comment by c0debreaker** [comment] 2016-08-16 15:26
I got it

**Comment by Nooby4Ever** [comment] 2016-08-16 15:28
Al right, btw: Bunselabs has one of the rather more active conky communities on their [forum](https://forums.bunsenlabs.org/viewforum.php?id=9).

(if the issue is solved please close it)

**Closed** 2016-08-16 16:09 UTC
