### ISSUE TITLE
[Bug]: latest version of Conky prints extraneous technical detail (or indicates a problem?) upon ctrl-C

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [brndnmtthws/conky#1537] opened 2023-05-17 03:46 UTC
### What happened?

When running Conky in a terminal (via `conky -c <pathToMyConkyConfig>`), and aborting via ctrl-C, I see:

```
conky: desktop window (2a061e5) is subwindow of root window (776)
conky: window type - desktop
conky: drawing to created window (0x6a00002)
conky: drawing to double buffer
^Cconky: received SIGHUP, SIGINT, or SIGTERM to terminate. bye!
conky: fccache.c:795: FcCacheFini: Assertion `fcCacheChains[i] == NULL' failed
```

And then Conky aborts. The problem is the last line. That line is unhelpful and was not present in the previous version of Conky that I ran - that previous version being 1.18.2. And I notice in the changelog that in the most recent release there was some change to error-handling. [_Edited_ to correct the version number.]

I am on Linux Mint  21.1 Cinnamon, which is based on Ubuntu 22.04.

### Version

1.19.2_pre

### Which OS/distro are you seeing the problem on?

Linux (other)

### Relevant log output

```Shell
conky: desktop window (2a061e5) is subwindow of root window (776)
conky: window type - desktop
conky: drawing to created window (0x6a00002)
conky: drawing to double buffer
^Cconky: received SIGHUP, SIGINT, or SIGTERM to terminate. bye!
conky: fccache.c:795: FcCacheFini: Assertion `fcCacheChains[i] == NULL' failed
```

**Comment by Caellian** [comment] 2024-04-19 16:30
Interesting, do you mind sharing your config? I'd like to see what font related settings you use.

**Comment by brndnmtthws** [comment] 2024-04-19 16:51
It's an issue related to https://github.com/brndnmtthws/conky/pull/1755. It's odd that you're getting the error, it would be helpful to know what version of libfontconfig you have installed. As you can see there aren't any calls to `FcFini()` anymore, but something else might be calling it: https://github.com/search?q=repo%3Abrndnmtthws%2Fconky%20FcFini&type=code

**Comment by Caellian** [comment] 2024-04-19 17:00
@brndnmtthws the issue is older, I was going through issues with `triage`.

Closing as the PR addresses this issue.

**Closed by Caellian** 2024-04-19 17:00 UTC
Labels: bug, display: x11

**Comment by brndnmtthws** [comment] 2024-04-19 17:19
> @brndnmtthws the issue is older, I was going through issues with `triage`.
> 
> Closing as the PR should've fixed this issue.

OIC, didn't notice the timestamp :)
