### ISSUE TITLE
Conky looks glitchy with messed up fonts in KDE plasma autostart

### ISSUE THREAD

**Issue by hethkar** [brndnmtthws/conky#199] opened 2016-01-11 00:03 UTC
Hello i am using Desktop: KDE Plasma 5.4.3 Distro: openSUSE Leap 42.1
and i have 'conky -b'(also tried 'conky') in autostart (from Startup and shutdown in System Settings). So whenever i start my system, conky looks bugged with blurred and overwritten fonts with little white background showing here and there as in the image attached.
Checked if two instances are running or not with 
ps -ef | grep conky | grep -v grep
And i see only one instance of conk running. Restarting plasma(with alt+ctrl+backspace) fixes it or even running new conky from command line also looks fine.
 how to fix this ?

![conky bugged](https://cloud.githubusercontent.com/assets/1507788/12224889/66e05e12-b821-11e5-9051-75c586778f69.jpeg)

**Comment by chepioq** [comment] 2016-01-12 16:50
In the system-settings of KDE, have you checked the case "Start with an empty session" in 
Startup and Shutdown ==> Desktop Session ?

**Comment by suknight** [comment] 2016-01-12 17:27
@chepioq  Yes it is set to "Start with an empty session" only

**Comment by chepioq** [comment] 2016-01-21 05:58
Can you show us the conky's part before " conky.text = [[ " ?

**Comment by lasers** [comment] 2018-08-09 01:29
2 years 7 months passed. Can you determine if you're still having this problem today on `1.10.8` or preferably `1.10.9_pre` (git)? The older versions are not trustworthy due to too many changes that can be hard to track. Additionally, I'd like to see configs too so we know what variables are being used... and if we can reproduce this issue easily. Thank you.

**Comment by lasers** [comment] 2018-08-09 14:36
Duplicate #218. Closing.

**Closed by lasers** 2018-08-09 14:36 UTC
