### ISSUE TITLE
downspeedgraph and upspeedgraph displays exactly the same

### ISSUE THREAD

**Issue by PacoPemo** [brndnmtthws/conky#979] opened 2020-06-20 02:59 UTC
```
${offset 15}${color green}${font}DL $color${downspeed eno1} ${alignr}${color green}UL $color${upspeed eno1}
${offset 15}${color black}${downspeedgraph eno1 32,120 0BF14A 0BF14A-t}${color black}${upspeedgraph eno1 32,120 F10E0B F10E0B-t}
```

As I describe in the title, I've found that downspeedgraph and upspeedgraph displays exactly the same information, and different from downspeed and upspeed.
Is there a fix?
![Captura de pantalla_2020-06-19_21-58-31](https://user-images.githubusercontent.com/60492860/85189838-12d52680-b278-11ea-8fc8-a85c00765aef.png)

Thanks.

**Comment by ernesto1** [comment] 2020-08-16 16:44
My conky has also gone out of whack with a recent system update.  I want to compare notes with you.
I'm running version `1.11.6_pre` on fedora 31.  What are you on?

For me the `downspeedgraph` and `upspeedgraph` are just displaying erratic graphs.  That have nothing to do with the actual speeds tracked by `downspeed` and `upspeed`.

`top_mem mem <any number>` is also evaluating to `'  inf '`

**Comment by PacoPemo** [comment] 2020-08-17 17:58
I’m sorry.  Not using Conkey anymore.  Too troublesome 
Best regards
Pemo


Enviado desde mi iPhone

**Comment by LinuxOnTheDesktop** [comment] 2022-03-02 19:55
I seem to have the same problem.

**Comment by starvald** [comment] 2022-08-24 20:07
i found they broke the graphs after 1.11.5, after that the scale option is ignored. it will max out the graph on very little data.

**Comment by LinuxOnTheDesktop** [comment] 2023-08-25 23:56
I believe that the problem persists.

**Comment by omani** [comment] 2023-09-15 12:59
this problem persists. sad to see how the maintainer is ignoring this issue.

**Comment by ernesto1** [comment] 2024-02-02 03:15
Not quite a solution but like @starvald mentioned --if your distro allows it-- downgrade conky to version 1.11.5.

I was able to do this in fedora up to v37.  But now on Fedora 39 I would have to compile conky from source in order to be able to downgrade to said version.  Has anyone compiled conky from source?

**Comment by LinuxOnTheDesktop** [comment] 2024-02-02 14:20
I compile Conky from source, but in a semi-automated, and not very transferable, way: I have a Bash script and a Bash library; and both are tailored somewhat for my computers. Still, I could make that code available. Note: there are instructions ([here](https://github.com/brndnmtthws/conky/wiki/Installation)); and the installation process does in parts use [an ncurses interface](https://en.wikipedia.org/wiki/Ncurses).

**Comment by ernesto1** [comment] 2024-02-03 16:46
@LinuxOnTheDesktop what distro are you on? what version of conky are you compiling?

**Comment by Caellian** [comment] 2024-04-12 19:39
Looks like a duplicate of  #1034. I just tested this locally with speedtest and by downloading a torrent - the graphs aren't the same.

_They look the same_ because they're both individually scaled with respect to max value they're showing. Due to how internet works, most requests (upload) are followed by a response (download), and vice versa - so the graphs will look similar, but their values aren't.

**Closed by Caellian** 2024-04-12 19:39 UTC
