### ISSUE TITLE
inserting pywal colors

### ISSUE THREAD

**Issue by icf20** [brndnmtthws/conky#404] opened 2017-07-20 20:12 UTC
i try to put this in conkyrc
`${exec tail -n 15 .cache/wal/colors.sh|sed "s/[=\'#]/ /g" }`

but i get 
`conky: [string "..."]:151: [string "converted config"]:54: unexpected symbol near '$'`

`tail -n 15 .cache/wal/colors.sh|sed "s/[=\'#]/ /g" `
give me

```
color1   4EB2AF 
color2   5AC2BA 
color3   6DC9B9 
color4   6ECAC6 
color5   99D5B8 
color6   B9CEB5 
color7   E1F2DE 
color8   a1a1a1 
color9   4EB2AF 
color10   5AC2BA 
color11   6DC9B9 
color12   6ECAC6 
color13   99D5B8 
color14   B9CEB5 
color15   E1F2DE 
```

what i am doing wrong here ?

**Comment by dbriba** [comment] 2017-07-21 04:24
Give us the contents of your script colors.sh

**Comment by icf20** [comment] 2017-07-21 06:22
> Give us the contents of your script colors.sh 

is not a script is just a way to score the information by pywall

```
# Shell variables
# Generated by 'wal'
wallpaper='.wal/oqDDYrAFwvKSufAHEtKAOQ_1.jpg'

# Special
background='#34301E'
foreground='#BDC2CA'
cursor='#BDC2CA'

# Colors
color0='#34301E'
color1='#7B826E'
color2='#9B8E50'
color3='#968A69'
color4='#627186'
color5='#7B848D'
color6='#9B9FA2'
color7='#BDC2CA'
color8='#999999'
color9='#7B826E'
color10='#9B8E50'
color11='#968A69'
color12='#627186'
color13='#7B848D'
color14='#9B9FA2'
color15='#BDC2CA'
```

**Comment by dbriba** [comment] 2017-07-23 04:32
Ok, I think your issue is in your conkyrc:
conky: [string "..."]:151: [string "converted config"]:54: unexpected symbol near '$'

Give us your conky.

**Comment by icf20** [comment] 2017-07-25 08:53
https://github.com/icf20/conkyrc/blob/master/conkyrc  i also tested this converted using the lua script

**Comment by dbriba** [comment] 2017-07-25 09:18
what is your conky's version?
1.9 or 1.10 ?
To know in console type 
conky -v

**Comment by icf20** [comment] 2017-07-25 09:19
1.10

**Comment by dbriba** [comment] 2017-07-25 19:12
Ok I think that the problem is here.
Your config is for conky 1.9, and you must transform it in the new syntax for 1.10.
With conky 1.10 there  is a script which transform conky 1.9 syntax to the 1.10, but sometimes the transformation is not complete.
And you have this type of error.

**Comment by icf20** [comment] 2017-07-31 10:27
for example if i take this config 
https://raw.githubusercontent.com/Dobbie03/dobbies-conky/master/s11.conkyrc

and replace the colour part with `${exec tail -n 16 .cache/wal/colors.sh|sed "s/$/,/g", }`
i get
`.conky/conkyrc:38: unexpected symbol near '$') while reading config file. 
conky: Assuming it's in old syntax and attempting conversion.
conky: [string "..."]:139: attempt to index a nil value (local 'settings')
`

**Comment by lasers** [comment] 2018-08-04 01:02
A year and two weeks passed. I suppose you don't need this issue to stay opened. Closing.

**Closed by lasers** 2018-08-04 01:02 UTC

**Comment by Vintodrimmer** [comment] 2018-11-03 20:20
I have the same question.

I'm trying to run `${exec sed -n 11,19p ~/.cache/wal/colors.sh}` inside the `concy_config = {}` segment and get the following error:
```
conky: Syntax error (/home/eichhorn/.config/conky/conky.conf:39: unexpected symbol near '$') while reading config file.
conky: Assuming it's in old syntax and attempting conversion.
conky: [string "..."]:139: attempt to index local 'settings' (a nil value)
```

How do I do that correctly?

**Comment by gibranlp** [comment] 2020-02-20 05:28
Is this thing fixed, can anyone show how to import colors from pywal to conky for version 1.11 of conky.

Cheers

**Comment by AlecsFerra** [comment] 2020-06-08 16:25
Bump

**Comment by Nate-Wilkins** [comment] 2022-03-04 20:35
You can do this by invoking `execpi` in the conky config file.

`conky_config`
```
conky.text = [[
${voffset 10}$font${execpi 15 /usr/bin/conky_echo_color color3}${execi 10000 awk -F= '/TION/ {print $2}' /etc/lsb-release |sed 's/"//g'}
]]
```

`/usr/bin/conky_echo_color`
```
#!/bin/bash

source ~/.cache/wal/colors.sh

echo "\${color $(eval echo \$$1)}"
```
