### ISSUE TITLE
[Bug] [3rd party?]: #conky:frens.io unavailable

### ISSUE THREAD

**Issue by ctrlcctrlv** [brndnmtthws/conky#1648] opened 2023-10-14 05:44 UTC
### What happened?

![image](https://github.com/brndnmtthws/conky/assets/838783/92c9781b-eb1f-4d50-95a6-82bda3a546f8)

maybe because i am not own matrix.org homeserver?

![image](https://github.com/brndnmtthws/conky/assets/838783/2ab48ef8-6d54-4016-9f20-8359bc81869c)

### Version

n/a

### Which OS/distro are you seeing the problem on?

Linux (other)

**Comment by brndnmtthws** [comment] 2023-10-14 13:08
Oh weird, it's working for me, but let me try to figure out what's going on. Perhaps I need to update synapse.

**Comment by InnocentZero** [comment] 2023-11-12 08:11
I am on homeserver `matrix.org` and I am still facing the same issue. I am using fractal matrix client. 

![ps_20231112133933](https://github.com/brndnmtthws/conky/assets/106757172/ba8db00a-82f0-4a6c-b8dd-64b71d473430)

![ps_20231112134004](https://github.com/brndnmtthws/conky/assets/106757172/78f95ae0-c746-4e4e-83e6-01999ac1298c)

Any idea what I'm doing wrong? @brndnmtthws

**Comment by siliconsniffer** [comment] 2024-02-24 08:58
Same issue for me, matrix doing matrix things apparently.

**Comment by brndnmtthws** [comment] 2024-04-20 13:56
Took me a while, but I figured out what's wrong: the URL should be matrix.frens.io not frens.io.

[Try this](https://matrix.to/#/#conky:matrix.frens.io).

**Comment by Caellian** [comment] 2024-04-20 14:31
Even with `matrix.frens.io` it doesn't work (using Element nor Web UI). Checked network responses and server responds with `502 Bad Gateway` (both with and without `matrix.`).

![image](https://github.com/brndnmtthws/conky/assets/4082795/b962c7e7-a62f-4722-bdb0-1d8fccbbc00d)

Can you try transferring to another instance? (gitter.im, libera.chat, matrix.org)

**Comment by brndnmtthws** [comment] 2024-04-20 14:39
Can you show the headers tab for that? It looks like the error is from `matrix-client.matrix.org`, which is a bit confusing. I'm also not using cloudflare, so the error doesn't make sense.

I've tested with https://app.element.io/#/room/#conky:matrix.frens.io and https://element.frens.io/#/room/#conky:frens.io, both seem to work.

**Comment by brndnmtthws** [comment] 2024-04-20 14:59
I've added SRV records for clients using DNS for service discovery. Perhaps that will help.

**Comment by Caellian** [comment] 2024-04-20 15:41
> I've added SRV records for clients using DNS for service discovery. Perhaps that will help.

Still same.

**Comment by brndnmtthws** [comment] 2024-04-20 17:26
I spent a while debugging this, and it came down to some config setting [as described in this issue](https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/2480). The `frens.io` domain is the correct one after all, but both seem to work in my testing.

In any case, I think it's properly working now, the issue only seemed to affect federated clients. I'll revert #1850 as that should stay as-is.

**Comment by Caellian** [comment] 2024-04-21 02:15
> Can you show the headers tab for that?

Sorry, didn't see this in the comment before the one I responded to.

> In any case, I think it's properly working now, the issue only seemed to affect federated clients.

I can confirm it's working, entered the room and the server shows green on electron now:
![image](https://github.com/brndnmtthws/conky/assets/4082795/fbdd9f54-4116-430a-92a3-1c574f97e9d0)

**Closed** 2024-04-21 02:16 UTC
Labels: bug
