### ISSUE TITLE
Segfaults if ipv6 switched off at kernel level

### ISSUE THREAD

**Issue by mcfadzgit** [brndnmtthws/conky#105] opened 2015-07-03 08:38 UTC
Using the conky-1.10.0-2-x86_64.pkg.tar.xz package from Arch's Extra repo.
I have ipv6 switched off at the kernel level by using the parameter: `ipv6.disable=1`
Conky segfaults immediately, regardless of configuration.
Can only be solved by modifying PKGBUILD cmake command to include:
`-D BUILD_IPV6=OFF \`
makepkg can then build the package and once installed, Conky runs as expected.

**Comment by marcpayne** [comment] 2015-07-04 06:35
I've tracked down the cause of this segfault. Until I figure out how to use git without breaking anything, I'll just describe the fix. In `linux.cc:647`, you call `fclose(file)`, but `file` might be `NULL`. Moving the `fclose()` call up into the `if` statement fixes the problem for me.

**Comment by marcpayne** [comment] 2015-11-29 00:56
@mcfadzgit Fixed in 1.10.1, so this issue can be closed now.

**Closed** 2015-11-29 17:11 UTC
