### ISSUE TITLE
[Bug]: Conky doesn't show a window on Wayland

### ISSUE THREAD

**Issue by kleshas** [brndnmtthws/conky#1960] opened 2024-06-05 23:46 UTC
### What happened?

Running sway, updated arch (new install). AMD 6750XT

Not sure when it started but recently my previously-working config only shows a blank window.  I saw a link on google saying this can be caused by an external IP lookup happening too often, but removing that from my config didn't help.

When out_to_x=true, out_to_wayland=false I get a blank conky window.  When out_to_x=false, out_to_wayland=true I don't get a window at all (though there is a conky running in htop).

Actually, it seems that the window DOES eventually populate, but after a few mins, and it seems to not be doing any further updates (I have a time entry in the config, it hasn't changed for 5 mins).

With out_to_wayland=true there is no change using own_window_type override, desktop or normal.
Running from command line:
conky -c ~/.conkyrc
conky: drawing to single buffer
conky: FOUND: console
conky: FOUND: ncurses
conky: FOUND: file
conky: FOUND: x11
conky: FOUND: wayland

and nothing after.

conky-cairo (1.21.2) has the error:  "unknown setting out_to_wayland, and Unable to find a usable display output when using out_to_wayland=true

### Version

all from 1.18

### Which OS/distro are you seeing the problem on?

Arch Linux

### Conky config

```Lua
conky.config = {

out_to_x=false,
out_to_wayland=true,
font = 'Liberation Mono Regular:size=10',
background = false,
cpu_avg_samples = 2,
diskio_avg_samples = 10,
double_buffer = true,
if_up_strictness = 'address',
net_avg_samples = 2,
no_buffers = true,
temperature_unit = 'celsius',
text_buffer_size = 2048,
update_interval = 1,
imlib_cache_size = 0,
alignment = 'top_left',
gap_x = 0,
gap_y = 0,
minimum_height = 600,
minimum_width = 350,
maximum_width = 350,
border_outer_margin = 1,
border_width = 1,
default_bar_width = 250,
default_bar_height = 10,
default_gauge_height = 25,
default_gauge_width = 40,
default_graph_height = 40,
default_graph_width = 153,
default_shade_color = '#000000',
default_outline_color = '#000000',
draw_borders = false,
draw_graph_borders = true,
draw_shades = false,
draw_outline = false,
stippled_borders = 0,
extra_newline = false,
format_human_readable = true,
max_text_width = 0,
max_user_text = 16384,
short_units = true,
top_name_width = 21,
top_name_verbose = false,
uppercase = false,
use_spacer = 'none',
use_xft = true,
xftalpha = 1,
own_window = true,
own_window_argb_value =255,
own_window_argb_visual = true,
own_window_class = 'Conky',
own_window_transparent = false,
own_window_title = 'system_conky',
own_window_type = 'normal',
format_human_readable = true,

default_color = '1A4770', -- Window border
}

conky.text = [[
Memory Usage
 ]]
```

**Comment by kleshas** [comment] 2024-06-06 04:29
looks like AirVPN was causing the blank screen.  Mullvad VPN doesn't have this issue.  I do still have the issue with out_to_wayland=true not working.

**Comment by yesrod** [comment] 2024-09-05 20:27
Having the same issue with `out_to_wayland = true` not displaying any window.

The issue started somewhere between versions 1.19.6 and 1.21.6.  With the deb package in Ubuntu 24.04 (1.19.6), I can still see a window when using Wayland.  With the 1.21.6 AppImage, the window is blank as described.

I'll download some other AppImage versions and see if I can find the exact version where this issue began.

**Comment by Caellian** [comment] 2024-10-02 21:52
`own_window_type` does nothing on Wayland. In future, it should allow configuring window to require sizing/placement like X11 counterparts, for now it's always on the background layer of `zwlr-layer-shell`.

**Comment by Caellian** [comment] 2024-10-04 15:32
Closed issue confirms this bug on KDE besides Sway, so I'm merging them here as this one is older.

**Comment by Caellian** [comment] 2024-10-04 15:33
Related to #1916

**Comment by Caellian** [comment] 2024-11-22 10:05
@abkein confirms this issue on Hyprland as well.

Running `hyprctl` reveals that window is mapped, focusable, and should be visible:
```
Window 5ef2019dbb90 -> ./src/conky:
	mapped: 1
	hidden: 0
	at: 2,28
	size: 956,1050
	workspace: 3 (3)
	floating: 0
	pseudo: 0
	monitor: 0
	class: kitty
	title: ./src/conky
	initialClass: kitty
	initialTitle: kitty
	pid: 687435
	xwayland: 0
	pinned: 0
	fullscreen: 0
	fullscreenClient: 0
	grouped: 0
	tags: 
	swallowing: 0
	focusHistoryID: 1
```

So this probably has something to do with how buffers are drawn/swapped.

**Comment by Bluey26** [comment] 2024-11-22 10:09
Hi, i can confirm this also happens in labwc (wlroots based). It works if i use it via xwayland, but if wayland fallback is enabled and selected, there is no window.

**Comment by Caellian** [comment] 2024-12-07 19:16
#2103 was merged. Can you verify whether this issue persists?

**Closed** 2024-12-07 20:44 UTC
Labels: bug, display: wayland, priority: severe

**Comment by Bluey26** [comment] 2024-12-07 20:59
Hi, just compiled the git master branch(after the 2 commits) using `-D BUILD_WAYLAND=ON` on my system. After that i added.

`out_to_wayland = true` and removed `out_to_x=true,`

But this had shown an issue, at least in my side:

`conky-git/src/conky/src/display-wayland.cc:691]: conky: defining struts` is constantly prompt when launching conky with:

`conky -D`

and the colors of the bars and graphs is darker now(the xwayland version has the bright colors). I recall this has been solved for the xwayland version in the past, should i open a separated issue for the wayland backend or its already known?

**Comment by Bluey26** [comment] 2024-12-07 21:10
There seems to be a x11 regression. The panel is shown in the wrong position, not respecting the own_window_type (dock) and not loading the transparency.

**Comment by Caellian** [comment] 2024-12-07 21:22
> `conky: defining struts` is constantly prompt when launching conky with: `conky -D`

That's a normal debug message. It shows up when window size changes.

> colors of the bars and graphs is darker now(the xwayland version has the bright colors)

I tested this, default white color shows up correctly for me on hyprland. Using `#ff0000` also shows pure red color.

> should i open a separated issue for the wayland backend or its already known?

[Refer to open wayland issues](https://github.com/brndnmtthws/conky/issues?q=is%3Aopen+is%3Aissue+label%3A%22display%3A+wayland%22). Before opening the issue please check:
- whether you're setting conky to be transparent,
- or have some other window drawing over it.

> Thanks for the fix. 

Thank @stacyharper. She's to blame for these fixes.

**Comment by Bluey26** [comment] 2024-12-07 21:33
Yes, the color issues seems to be related to #1504
setting `own_window_argb_value = 255,` shows the "correct" colors in the wayland backend.

**Comment by abkein** [comment] 2024-12-07 21:44
Can confirm the last PR fixed the problem

**Comment by Caellian** [comment] 2024-12-08 03:06
> There seems to be a x11 regression. The panel is shown in the wrong position, not respecting the own_window_type (dock) and not loading the transparency.
> 
> **Update:** The issue is gone when downgrading to `conky-git-1.21.7.r5.g71814776-1-x86_64.pkg.tar`

That's  #2029.
