### ISSUE TITLE
[Bug]: Conky 1.17.0-1 ignores second monitor and xinerama_head=1 config. Downgrading to 1.15.0-1 puts it back on the correct second monitor.

### ISSUE THREAD

**Issue by ipaqmaster** [brndnmtthws/conky#1372] opened 2023-01-16 00:33 UTC
### What happened?

Latest version seems to ignore my xinerama_head setting. Downgraded to the last version I have in cache here and positioning appears to be restored.

### Version

1.17.0-1

### Which OS/distro are you seeing the problem on?

Arch Linux

**Comment by hrshadhin** [comment] 2023-01-16 03:16
I'm also facing same issue.

**Comment by lantorax** [comment] 2023-01-16 17:17
I have this on my laptop, but my desktop works fine:
Laptop (broken):extra/conky 1.17.0-1 [installed]
Desktop (not broken): aur/conky-git 1.15.0.r2.g186f2162-2

Same on both boxes: linux: 6.1.5.arch2-1

.conkyrc is largely the same, just box specific things changed

**Comment by dbenedb** [comment] 2023-01-16 21:02
Duplicate of: https://github.com/brndnmtthws/conky/issues/1364

**Comment by ipaqmaster** [comment] 2023-01-22 22:44
Did my Arch updates this morning with a reboot and 1.17.0-1 seems to stick to the correct monitor now. Maybe a dependency had trouble?

**Comment by ViejoRS** [comment] 2023-01-24 02:50
I am also having this issue on Arch with 1.17.0

**Comment by ipaqmaster** [comment] 2023-02-07 03:35
This seems to have resumed for me on all machines with 1.17.0 appearing in my upgrade list again. Have to continue downgrading to 1.15.0 to use conky in a manner which will actually be visible on my desktops.

**Closed** 2023-02-18 14:58 UTC
Labels: bug
