### ISSUE TITLE
[Bug]: own_window = false doesnt' seems to works anymore undex x

### ISSUE THREAD

**Issue by stacyharper** [brndnmtthws/conky#1410] opened 2023-02-20 10:53 UTC
### What happened?

I got this config file which works very well under Wayland now. But now it fails under x11. 

Conky is expected display over the bg, and contain a simple "foo bar".

If I add own_window = true it then works

I got no backtrace but I pasted the -D output

### Version

master

### Which OS/distro are you seeing the problem on?

Linux (other)

### Conky config

```Lua
conky.config = { 
    out_to_wayland = true, 
    alignment = 'middle_middle', 
    own_window_argb_value = 0, 
    default_shade_color = 'grey', 
    draw_shades = true, 
    font = 'Mono:size=13', 
    update_interval = 5, 
} 
 
conky.text = [[ 
foo bar 
]]
```

### Relevant log output

```Shell
DEBUG(0) [/mnt/sd/home/stacy/sources/conky/src/conky.cc:1953]: reading contents from config file '/mnt/sd/home/stacy/.config/sxmo/conky.conf'
DEBUG(0) [/mnt/sd/home/stacy/sources/conky/src/x11.cc:233]: enter init_x11()
DEBUG(0) [/mnt/sd/home/stacy/sources/conky/src/x11.cc:322]: Fixed xinerama area to: 0 0 720 1440
DEBUG(0) [/mnt/sd/home/stacy/sources/conky/src/x11.cc:271]: leave init_x11()
DEBUG(0) [/mnt/sd/home/stacy/sources/conky/src/x11.cc:487]: enter x11_init_window()
DEBUG(0) [/mnt/sd/home/stacy/sources/conky/src/x11.cc:322]: Fixed xinerama area to: 0 0 720 1440
conky: desktop window (1e2) is root window
conky: drawing to desktop window
DEBUG(0) [/mnt/sd/home/stacy/sources/conky/src/x11.cc:870]: leave x11_init_window()
conky: wl_display_connect: No such file or directory
conky: X Error: type 0 Display ffffbee4e600 XID 482 serial 58 error_code 10 request_code 2 minor_code 0 other Display: ffffbee4e600

Aborted
```

**Comment by wladmis** [comment] 2023-06-04 14:18
After bisecting I found that first commit that broke this option was brndnmtthws/conky@8afa62d88944247759d7144a2734afcac600c777 (really idk why).

**Comment by Caellian** [comment] 2024-04-19 17:48
I know why :point_right: :point_left:... The bisected commit only enables problematic code from one of previous commits. I believe this issue was caused because `own_window_type` defaulted to `normal` and `own_window` wasn't checked so code tried registering events on `root` and `desktop` windows which caused Errors and because I didn't yet stop errors from closing Conky this meant it aborted.

I believe this error was fixed in one of subsequent versions.

I can't reproduce with `main` so I'm closing this issue (I'm sure I experienced it myself at some point). If you however still experience this, let me know and I'll reopen the issue.

**Closed** 2024-04-19 17:48 UTC
Labels: bug
