### ISSUE TITLE
[Bug]: OpenBSD 7.6 Conky version 1.9.0p24 ${cpu cpuX} (X >= 1) always zero

### ISSUE THREAD

**Issue by epsheldoni** [brndnmtthws/conky#2074] opened 2024-11-07 23:26 UTC
### What happened?

I cannot get conky to display CPU usage in percents.

### Version

1.9.0p24 from OpenBSD packages

### Which OS/distro are you seeing the problem on?

Linux (other)

### Conky config

```Lua
background no
use_xft yes
xftfont monospace:size=9
xftalpha 1
update_interval 1.0
total_run_times 0
own_window yes
own_window_type normal
own_window_transparent yes
own_window_hints undecorated,below,sticky,skip_taskbar,skip_pager
own_window_argb_visual yes
own_window_argb_value 192
minimum_size 1 1
maximum_width 280
draw_shades no
draw_outline no
draw_borders no
draw_graph_borders no
default_color white
default_shade_color 000000
default_outline_color d9d7d6
alignment mr
gap_x 12
gap_y 12
double_buffer yes
uppercase no
cpu_avg_samples 2
override_utf8_locale no
color1 blue
color2 gray

##############################################
#  Output
##############################################
TEXT
Host:$alignr $nodename
Architecture:$alignr $machine
Kernel:$alignr $kernel
Freq$alignr ${freq}MHz
Uptime:$alignr $uptime
RAM:$alignr $mem/$memmax
Disk usage:$alignr ${fs_used /}/${fs_size /}

CPU  0 usage:$alignr  ${cpu cpu0}%
CPU  1 usage:$alignr  ${cpu cpu1}%
CPU  2 usage:$alignr  ${cpu cpu2}%
CPU  3 usage:$alignr  ${cpu cpu3}%
CPU  4 usage:$alignr  ${cpu cpu4}%
CPU  5 usage:$alignr  ${cpu cpu5}%
CPU  6 usage:$alignr  ${cpu cpu6}%
CPU  7 usage:$alignr  ${cpu cpu7}%
CPU  8 usage:$alignr  ${cpu cpu8}%
CPU  9 usage:$alignr  ${cpu cpu9}%
CPU 10 usage:$alignr ${cpu cpu10}%
CPU 11 usage:$alignr ${cpu cpu11}%
CPU 12 usage:$alignr ${cpu cpu12}%
CPU 13 usage:$alignr ${cpu cpu13}%
CPU 14 usage:$alignr ${cpu cpu14}%
CPU 15 usage:$alignr ${cpu cpu15}%

System Load:  $alignr${loadavg}   

Processes ${hr 1}
${top name 1}${alignr}${top cpu 1}
${top name 2}${alignr}${top cpu 2}
${top name 3}${alignr}${top cpu 3}
${top name 4}${alignr}${top cpu 4}
${top name 5}${alignr}${top cpu 5}
${top name 6}${alignr}${top cpu 6}
${top name 7}${alignr}${top cpu 7}
${top name 8}${alignr}${top cpu 8}
${top name 9}${alignr}${top cpu 9}

Network iwx0 ${hr 1}
Down: $color${downspeed iwx0} - ${alignr}Up: ${upspeed iwx0} -
${downspeedgraph iwx0 25,140 CCCCCC 0000FF} ${alignr}${upspeedgraph iwx0 25,140 000000 00ff00} $color
Total: ${totaldown iwx0} ${alignr}Total: ${totalup iwx0}
```

**Comment by Caellian** [comment] 2024-11-07 23:32
Closing as duplicate of #1376.

**Closed by Caellian** 2024-11-07 23:32 UTC
Labels: bug, cpu, text, os: openbsd
