### ISSUE TITLE
start with 'conky  -b' crashed

### ISSUE THREAD

**Issue by wxg4net** [brndnmtthws/conky#28] opened 2013-10-28 11:22 UTC
conky: desktop window (26c) is root window
conky: window type - desktop
conky: drawing to created window (0x2200002)
conky: drawing to double buffer
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  62 (X_CopyArea)
  Serial number of failed request:  448
  Current serial number in output stream:  450

**Comment by dmccombs** [comment] 2015-03-18 23:10
I'm seeing this as well with the latest git (commit 9c833665d8aba5bd8547b5b0c5024a063c62ea02). If double_buffer is enabled, an X error is thrown and conky closes. Without double_buffer conky runs normally, but obviously there's a lot of flickering.

**Comment by dmccombs** [comment] 2015-03-18 23:50
It looks like this is just caused by BUILD_XDBE not being enabled in our builds. I enabled that in `ccmake` and rebuilt and all is well.

**Comment by stardiviner** [comment] 2015-06-30 23:54
I got the same error, and after bisect debug config file, it does caused by the line `double_buffer yes`.
I also get another link, https://bbs.archlinux.org/viewtopic.php?id=199217 after google.
Is conky breaking the backward compatible?

**Comment by lasers** [comment] 2018-08-03 15:42
@brndnmtthws Can we close this? `conky -b` works okay here.
```
1d [chris:~] % /usr/local/bin/conky -b
conky: no personal or system-wide config file found, using builtin default
conky: desktop window (25a) is root window
conky: window type - desktop
conky: drawing to created window (0x2600001)
conky: drawing to double buffer
                 _          
  ___ ___  _ __ | | ___   _ 
 / __/ _ \| '_ \| |/ / | | |
| (_| (_) | | | |   <| |_| |
 \___\___/|_| |_|_|\_\\__, |
                      |___/ 

conky: received SIGINT or SIGTERM to terminate. bye!
```
Logo represents a successful x11 conky.

**Closed** 2018-08-03 16:21 UTC
