### ISSUE TITLE
[Bug]: Conky doesn't start

### ISSUE THREAD

**Issue by maxulm** [brndnmtthws/conky#2008] opened 2024-08-05 16:47 UTC
### What happened?

Conky doesn't start anymore on current Arch.

### Version

1.21.5-1

### Which OS/distro are you seeing the problem on?

Arch Linux

### Conky config

```Lua
font = 'DejaVu Sans Mono:size=10',

....


${font Font Awesome 6 Free:style=Solid:size=12}↓${font}          ${downspeed enp0s31f6}
${font Font Awesome 6 Free:style=Solid:size=12}↑${font}          ${upspeed enp0s31f6}
```

### Relevant log output

```Shell
DEBUG(1) [/usr/src/debug/conky/conky/src/fonts.cc:64]: setting up fonts
DEBUG(1) [/usr/src/debug/conky/conky/src/fonts.cc:84]: loading fonts
DEBUG(1) [/usr/src/debug/conky/conky/src/conky.cc:638]: jumping
DEBUG(1) [/usr/src/debug/conky/conky/src/fonts.cc:84]: loading fonts
DEBUG(1) [/usr/src/debug/conky/conky/src/fonts.cc:64]: setting up fonts
DEBUG(1) [/usr/src/debug/conky/conky/src/fonts.cc:84]: loading fonts
DEBUG(1) [/usr/src/debug/conky/conky/src/conky.cc:638]: jumping
DEBUG(1) [/usr/src/debug/conky/conky/src/fonts.cc:84]: loading fonts
DEBUG(1) [/usr/src/debug/conky/conky/src/fonts.cc:64]: setting up fonts
DEBUG(1) [/usr/src/debug/conky/conky/src/fonts.cc:84]: loading fonts
DEBUG(1) [/usr/src/debug/conky/conky/src/conky.cc:638]: jumping
DEBUG(1) [/usr/src/debug/conky/conky/src/fonts.cc:84]: loading fonts
DEBUG(1) [/usr/src/debug/conky/conky/src/fonts.cc:64]: setting up fonts
DEBUG(1) [/usr/src/debug/conky/conky/src/fonts.cc:84]: loading fonts
DEBUG(1) [/usr/src/debug/conky/conky/src/conky.cc:638]: jumping
DEBUG(1) [/usr/src/debug/conky/conky/src/fonts.cc:84]: loading fonts
DEBUG(1) [/usr/src/debug/conky/conky/src/fonts.cc:64]: setting up fonts
DEBUG(1) [/usr/src/debug/conky/conky/src/fonts.cc:84]: loading fonts
DEBUG(1) [/usr/src/debug/conky/conky/src/conky.cc:638]: jumping
DEBUG(1) [/usr/src/debug/conky/conky/src/fonts.cc:84]: loading fonts
DEBUG(1) [/usr/src/debug/conky/conky/src/fonts.cc:64]: setting up fonts
DEBUG(1) [/usr/src/debug/conky/conky/src/fonts.cc:84]: loading fonts
DEBUG(1) [/usr/src/debug/conky/conky/src/conky.cc:638]: jumping
DEBUG(1) [/usr/src/debug/conky/conky/src/fonts.cc:84]: loading fonts
DEBUG(1) [/usr/src/debug/conky/conky/src/fonts.cc:64]: setting up fonts
```

**Comment by zlice** [comment] 2024-08-06 01:18
https://github.com/brndnmtthws/conky/issues/1939

**Comment by maxulm** [comment] 2024-10-03 13:40
> @maxulm Do you mind providing the following details so I can triage this issue better:
> 
> * Which WM/DE you're using? Is it wayland/X11?
> * Provide the whole script file. Just dump it here, I'll clean it up if needed.
> * How do you start conky? Is it with Xinitrc, WM/DE autostart script, manually?
>   
>   * Does the issue occur when started manually from the terminal?
> 
> Depending on those, there might be some additional questions I'll ask.

Hi,
thank you!

1. I'm using KDE 6.1 with wayland
2. See below
3. With KDE autostart, but the problem still occurs starting conky via terminal

`-- Conky, a system monitor https://github.com/brndnmtthws/conky
--
-- This configuration file is Lua code. You can write code in here, and it will
-- execute when Conky loads. You can use it to generate your own advanced
-- configurations.
--
-- Try this (remove the `--`):
--
--   print("Loading Conky config")
--
-- For more on Lua, see:
-- https://www.lua.org/pil/contents.html

conky.config = {
    alignment = 'top_right',
    background = false,
    border_width = 1,
    cpu_avg_samples = 2,
    default_color = '#FFFFFF',
    default_outline_color = '#FFFFFF',
    default_shade_color = '#FFFFFF',
    double_buffer = true,
    draw_borders = false,
    draw_graph_borders = true,
    draw_outline = false,
    draw_shades = false,
    extra_newline = false,
    font = 'DejaVu Sans Mono:size=10',
    gap_x = 60,
    gap_y = 60,
    minimum_height = 5,
    minimum_width = 5,
    net_avg_samples = 2,
    no_buffers = true,
    out_to_console = false,
    out_to_ncurses = false,
    out_to_stderr = false,
    out_to_x = false,
    out_to_wayland = true,
    own_window = true,
    own_window_class = 'Conky',
    own_window_type = 'dock',
    own_window_argb_visual = true,
    own_window_transparent = true,
    own_window_hints = 'below,skip_taskbar,sticky',
    show_graph_range = false,
    show_graph_scale = false,
    stippled_borders = 0,
    update_interval = 1.0,
    uppercase = false,
    use_spacer = 'none',
    use_xft = true
}

conky.text = [[
${color #808080}Info:$color ${scroll 32 $sysname $nodename $kernel $machine}
$hr
${color #808080}Uptime:$color $uptime
${color #808080}Frequency (in MHz):$color $freq
${color #808080}Frequency (in GHz):$color $freq_g
${color #808080}RAM Usage:$color $mem/$memmax - $memperc% ${membar 4}
#${color #808080}Swap Usage:$color $swap/$swapmax - $swapperc% ${swapbar 4}
${color #808080}CPU Usage:$color $cpu% ${cpubar 4}
${color #808080}Processes:$color $processes  ${color #808080}Running:$color $running_processes
$hr
${color #808080}File systems:
 / $color${fs_used /}/${fs_size /} ${fs_bar 6 /}
#${color #808080}Networking:
#Up:$color ${upspeed} ${color #808080} - Down:$color ${downspeed}
#$hr
${color #808080}Name              PID     CPU%   MEM%
${color #D3D3D3} ${top name 1} ${top pid 1} ${top cpu 1} ${top mem 1}
${color #D3D3D3} ${top name 2} ${top pid 2} ${top cpu 2} ${top mem 2}
${color #D3D3D3} ${top name 3} ${top pid 3} ${top cpu 3} ${top mem 3}
${color #D3D3D3} ${top name 4} ${top pid 4} ${top cpu 4} ${top mem 4}
$hr
${color #808080}wifi:${color}${if_up wlp3s0}
IP         ${addr wlp3s0}
GW         ${gw_ip wlp3s0}
SSID       ${wireless_essid wlp3s0}
strength   ${wireless_bitrate wlp3s0}
quality    ${wireless_link_qual wlp3s0}%
${endif wlp3s0}
$hr
${color #808080}lan:${color}${if_up enp0s31f6}
IP         ${addr enp0s31f6}
GW         ${gw_ip enp0s31f6}
${font Font Awesome 6 Free:style=Solid:size=12}↓${font}          ${downspeed enp0s31f6}
${font Font Awesome 6 Free:style=Solid:size=12}↑${font}          ${upspeed enp0s31f6}
${endif enp0s31f6}
${if_up ppp0}
${hr}
${color #808080}vpn:${color}
IP        ${addr ppp0}
GW        ${gw_ip ppp0}
${endif ppp0}

${hr}
battery load    ${battery_bar BAT1}
battery state   ${battery BAT1}
${hr}
#AGE	${execi 600 /usr/share/wiesneth/scripts/age} days
]]
`

**Comment by Caellian** [comment] 2024-10-03 17:33
Right, Wayland support is **very** WIP at the moment. There's a lot of things that don't work correctly.

Do you mind running `conky -DD` and pasting the whole debug output?

**Comment by Caellian** [comment] 2024-10-04 15:29
Closing as duplicate of #1960

**Closed** 2024-10-04 15:30 UTC
Labels: bug, display: wayland
