### ISSUE TITLE
[Bug]: Conky are only in window not at desktop on sway

### ISSUE THREAD

**Issue by muellerjoel** [brndnmtthws/conky#1916] opened 2024-05-14 19:29 UTC
### What happened?

![20240514_21h28m14s_grim](https://github.com/brndnmtthws/conky/assets/76882403/ddadedf0-51b1-46f5-b63e-a9e86d0630b8)

It's works but in a window not on top of the background. Why?

### Version

onky-git-1.21.0.r9.g2d507672-1-x86_64.pkg.tar.zst

### Which OS/distro are you seeing the problem on?

Arch Linux

### Conky config

```Lua
conky.config = {
    alignment = 'top_right',
    background = true,
    border_width = 1,
    cpu_avg_samples = 2,
    default_color = 'white',
    default_outline_color = 'white',
    default_shade_color = 'white',
    double_buffer = true,
    draw_borders = false,
    draw_graph_borders = true,
    draw_outline = false,
    draw_shades = false,
    extra_newline = false,
    font = 'Noto Sans Mono:size=12',
    gap_x = 20,
    gap_y = -30,
    border_inner_margin = 16,
    border_outer_margin = 8,
    minimum_height = 5,
    minimum_width = 5,
    net_avg_samples = 2,
    no_buffers = true,
    out_to_console = false,
    out_to_ncurses = false,
    out_to_stderr = false,
    out_to_wayland = true,
    own_window = true,
    own_window_argb_value = 255,
    own_window_argb_visual = true,
    own_window_class = 'Conky',
    own_window_hints = 'undecorated,sticky,below,skip_taskbar,skip_pager',
    own_window_transparent = true,
    own_window_type = 'desktop',
    show_graph_range = true,
    show_graph_scale = true,
    stippled_borders = 0,
    update_interval = 2.0,
    uppercase = false,
    use_spacer = 'none',
    use_xft = true,
}

conky.text = [[${voffset 4}${color}${font :bold}Lenovo Thinkpad X1 Extreme${font}
$hr
${color grey}Hostname: ${color}$nodename
${color grey}OS      : ${color}$sysname $kernel $machine
${color grey}Uptime  : ${color}$uptime
${color grey}Battery : ${color}$battery ${voffset 3}${battery_bar}${voffset -3}
${voffset 8}${color}${font :size=14}CPU ${font} (Intel Core i5-8400H @2.5GHz)$hr
${voffset 4}${color grey}Core 0: ${color}${alignr}${freq_g 1} GHz  ${color grey}Temperature: ${color}${execi 30 sensors | grep "Core 0" | awk '{print $3}'}
${color grey}Core 1: ${color}${alignr}${freq_g 2} GHz  ${color grey}Temperature: ${color}${execi 30 sensors | grep "Core 1" | awk '{print $3}'}
${color grey}Core 2: ${color}${alignr}${freq_g 3} GHz  ${color grey}Temperature: ${color}${execi 30 sensors | grep "Core 0" | awk '{print $3}'}
${color grey}Core 4: ${color}${alignr}${freq_g 4} GHz  ${color grey}Temperature: ${color}${execi 30 sensors | grep "Core 1" | awk '{print $3}'}
${voffset 8}${color grey}Thread 1: ${color}${voffset 3}${cpubar cpu1}${voffset -3}
${color grey}Thread 2: ${color}${voffset 3}${cpubar cpu2}${voffset -3}
${color grey}Thread 3: ${color}${voffset 3}${cpubar cpu3}${voffset -3}
${color grey}Thread 4: ${color}${voffset 3}${cpubar cpu4}${voffset -3}
${color grey}Thread 5: ${color}${voffset 3}${cpubar cpu5}${voffset -3}
${color grey}Thread 6: ${color}${voffset 3}${cpubar cpu6}${voffset -3}
${color grey}Thread 7: ${color}${voffset 3}${cpubar cpu7}${voffset -3}
${color grey}Thread 8: ${color}${voffset 3}${cpubar cpu8}${voffset -3}
${voffset 4}${color grey}Process              CPU%   MEM%
${color}  ${top name 1} ${top cpu 1} ${top mem 1}
${color}  ${top name 2} ${top cpu 2} ${top mem 2}
${color}  ${top name 3} ${top cpu 3} ${top mem 3}
${voffset 6}${color}${font :size=14}RAM ${font}$hr
${voffset 4}${color grey}Memory usage: ${color}${memperc}% of ${memmax} ${voffset 3}${membar}${voffset -3}
${voffset 4}${color grey}Process              MEM%   CPU%
${color}  ${top_mem name 1} ${top_mem mem 1} ${top_mem cpu 1}
${color}  ${top_mem name 2} ${top_mem mem 2} ${top_mem cpu 2}
${color}  ${top_mem name 3} ${top_mem mem 3} ${top_mem cpu 3}
${voffset 6}${color}${font :size=14}DISK ${font}$hr
${voffset 4}${color grey}Local root: $color${fs_free /} ${goto 215}${color grey}/ ${color} ${fs_size /}${goto 335}${voffset 3}${fs_bar /}${voffset -3}
${color grey}Home    : ${color}${fs_free /home} ${goto 215}${color grey}/ ${color}${fs_size /home}${goto 335}${voffset 3}${fs_bar /home}${voffset -3}
#${color grey}Google    : ${color}${fs_free /home/username/Cloud/GoogleDrive} ${goto 215}${color grey}/ ${color}${fs_size /home/username/Cloud/GoogleDrive}${goto 335}${voffset 3}${fs_bar /home/username/Cloud/GoogleDrive}${voffset -3}
#${color grey}OneDrive  : $color${fs_free /home/username/Cloud/OneDrive-Private} ${goto 215}${color grey}/ ${color}${fs_size /home/username/Cloud/OneDrive-Private}${goto 335}${voffset 3}${fs_bar /home/username/Cloud/OneDrive-Private}${voffset -3}
#${color grey}Dropbox   : $color${fs_free /home/username/Cloud/Dropbox} ${goto 215}${color grey}/ ${color}${fs_size /home/username/Cloud/Dropbox}${goto 335}${voffset 3}${fs_bar /home/username/Cloud/Dropbox}${voffset -3}
#${color grey}Mega      : $color${fs_free /home/username/Cloud/Mega} ${goto 215}${color grey}/ ${color}${fs_size /home/username/Cloud/Mega}${goto 335}${voffset 3}${fs_bar /home/username/Cloud/Mega}${voffset -3}
${color grey}NAS     : $color${fs_free /home/backup} ${goto 215}${color grey}/ ${color}${fs_size /home/backup}${goto 335}${voffset 3}${fs_bar /home/backup}${voffset -3}
#${voffset 3}${color grey}      Read: ${color}${diskio_read /dev/md0} ${goto 230}${color grey}Write: ${color}${diskio_read /dev/md0}
${if_existing /home/backup/"a file or a lock"} ${color grey}NAS : {fs_free /home/backup} ${goto 215}${color grey}/ ${color}${fs_size /home/backup}${goto 335}${voffset 3}${fs_bar /home/backup}${voffset -3}${endif}
${voffset -15}${color}${font :size=14}NETWORK ${font}$hr
${if_existing /proc/net/route wlp0s20f3}\
${if_existing /proc/net/route enp58s0u1u3c2}\
${voffset 4}${color grey}Warning: ${color}Both Wi-Fi and wired network active!
${else}\
${voffset 4}${color grey}ESSID: ${color}${wireless_essid wlp0s20f3}${goto 240}${color grey}Quality: ${color}${wireless_link_qual_perc wlp0s20f3}%
${voffset 4}${color grey}  IP : ${color}${addr wlp0s20f3}${goto 240}${voffset 8}${color grey}Down:${goto 300}${color}${downspeed wlp0s20f3}
${voffset -8}${color grey}  Zt : ${color}${addr zerotierdevice}${goto 240}${voffset 8}${color grey}Up  :${goto 300}${color}${upspeed wlp0s20f3}
${voffset -8}${color grey}  GW : ${color}${gw_ip}
${color grey}  PubIPv4 : ${color}${texeci 30 curl -L https://myipv4.p1.opendns.com/get_my_ip |  awk '{print substr($0, 8, length($0) - 9)}'}
${color grey}  PubIPv6 : ${color}${texeci 30 curl -L https://myipv6.p1.opendns.com/get_my_ip |  awk '{print substr($0, 8, length($0) - 9)}'}
${endif}\
${else}\
${if_existing /proc/net/route enp58s0u1u3c2}\
${voffset 4}${color grey}Wired network: ${color}Active
${voffset 4}${color grey}  IP : ${color}${addr enp58s0u1u3c2}${goto 240}${voffset 8}${color grey}Down:${goto 300}${color}${downspeed enp58s0u1u3c2}
${voffset -8}${color grey}  Zt : ${color}${addr zerotierdevice}${goto 240}${voffset 8}${color grey}Up  :${goto 300}${color}${upspeed enp58s0u1u3c2}
${voffset -8}${color grey}  GW : ${color}${gw_ip}
${color grey}  PubIPv4 : ${color}${texeci 30 curl -L https://myipv4.p1.opendns.com/get_my_ip |  awk '{print substr($0, 8, length($0) - 9)}'}
${color grey}  PubIPv6 : ${color}${texeci 30 curl -L https://myipv6.p1.opendns.com/get_my_ip |  awk '{print substr($0, 8, length($0) - 9)}'}
${endif}\
${endif}\
${voffset 6}${color}${font :size=14}UPDATES ${font}$hr
${voffset 4}${color grey}      Arch: ${color}${execi 600 checkupdates | wc -l }${goto 230}${color grey}AUR: ${color}${execi 600 auracle outdated | wc -l}
]]

AND
conky.config = {
    alignment = 'top_middle',
    background = true,
    border_width = 1,
    cpu_avg_samples = 2,
    default_color = 'grey',
    default_outline_color = 'white',
    default_shade_color = 'white',
    double_buffer = true,
    draw_borders = false,
    draw_graph_borders = true,
    draw_outline = false,
    draw_shades = false,
    extra_newline = false,
    font = 'Noto Sans Light:size=12',
    gap_x = -200,
    gap_y = -10,
    minimum_height = 5,
    minimum_width = 5,
    net_avg_samples = 2,
    no_buffers = true,
    out_to_console = false,
    out_to_ncurses = false,
    out_to_stderr = false,
    out_to_wayland = true,
    own_window = true,
    own_window_argb_value = 0,
    own_window_argb_visual = true,
    own_window_class = 'Conky',
    own_window_hints = 'undecorated,sticky,below,skip_taskbar,skip_pager',
    own_window_transparent = true,
    own_window_type = 'desktop',
    show_graph_range = false,
    show_graph_scale = false,
    stippled_borders = 0,
    update_interval = 1.0,
    uppercase = false,
    use_spacer = 'none',
    use_xft = true,
}

conky.text = [[
${font Noto Sans Light:size=40} ${time %A}${font}
${font Noto Sans Light:size=40} ${time %B} ${time %d}${font}
${font Noto Sans Light:size=40} ${time %Y}, week ${time %V}${font}
${font Noto Sans Light:size=80}${time %T}${font}
${voffset 10}${font Noto Sans Light:size=20}${alignr}${time %Z} (${time %z})${font}
]]
```

### Stack trace

```GDB
[morta@lapt0p conky]$ gdb conky
GNU gdb (GDB) 14.2
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from conky...

warning: the debug information found in "/usr/lib/debug//usr/bin/conky.debug" does not match "/usr/bin/conky" (CRC mismatch).
(No debugging symbols found in conky)
(gdb) run -c /etc/conky/.conkyrc
Starting program: /usr/bin/conky -c /etc/conky/.conkyrc
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
conky: desktop window (0x40b) is root window
conky: window type - desktop
conky: drawing to created window (0x400002)
conky: drawing to double buffer
conky: Unknown setting 'out_to_wayland'
[Detaching after fork from child process 55724]
conky: forked to background, pid is 55724
[Inferior 1 (process 55721) exited normally]
(gdb)
conky: FOUND: console
conky: FOUND: ncurses
conky: FOUND: file
conky: FOUND: x11
conky: 'sway' wayland session running '(null)' destop
sh: Zeile 1: auracle: Kommando nicht gefunden.
sh: Zeile 1: checkupdates: Kommando nicht gefunden.
(gdb)   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload    U%p lTooatda l    T o t%a lR e c eSipveendt  %   X fLeerfd t  A vSepreaegde
p e e0d       T i0m e      0  T i m e  0        T0i m e     C0u r r e n t
0             0   - - : - - : - -   - - : -  - : - -   - - : - - :D-l-o a d     U0pload   Total   Spent    Left  Speed
100    29  100    29    0     0     47      0 --:--:-- --:--:-- --:--:--    47
100    24  100    24    0     0     23      0  0:00:01  0:00:01 --:--:--    23
conky: X IO Error: Display 5555557bf520

(gdb) bt full
No stack.
```

**Comment by lineage-of-roots** [comment] 2024-05-14 20:03
As a temporary workaround, perhaps try adding in conkyrc file the lines

`out_to_x=false`
`out_to_wayland=true`


Also, during the  build, did you select `BUILD_WAYLAND=true`  ?

**Comment by muellerjoel** [comment] 2024-05-14 20:40
> As a temporary workaround, perhaps try adding in conkyrc file the lines
> 
> `out_to_x=false` `out_to_wayland=true`

Both doesn’t display anything 
> 
> Also, during the build, did you select `BUILD_WAYLAND=true` ?

Yes

**Comment by lineage-of-roots** [comment] 2024-05-15 10:29
Try removing the quotes from  'desktop' in `own_window_type`

just `desktop`  without the quotes.

**Comment by muellerjoel** [comment] 2024-05-15 16:18
> Try removing the quotes from 'desktop' in `own_window_type`
> 
> just `desktop` without the quotes.

no effect

**Comment by magdesign** [comment] 2024-05-16 05:33
i can confirm that release 1.21 broke something important on sway and conky does not display anything on desktop anymore (alpine/postmarketos, wayland/sway).

**Comment by 01micko** [comment] 2024-05-19 02:28
> i can confirm that release 1.21 broke something important on sway and conky does not display anything on desktop anymore (alpine/postmarketos, wayland/sway).

Also on labwc-0.7.2 debian/testing - shall await update in apt to 1.21.1 and see. Thanks.

**Comment by 01micko** [comment] 2024-05-19 02:40
Some context if it helps.

<details>
<summary>debug</summary>

```
mick@hp-labwc:~$ 
DEBUG(0) [./src/display-output.cc:39]: HTTP display output disabled. Enable by recompiling with 'BUILD_HTTP' flag enabled.
conky: FOUND: console
conky: FOUND: ncurses
conky: FOUND: file
conky: FOUND: x11
conky: FOUND: wayland
DEBUG(0) [./src/display-output.cc:109]: Initialized display output 'wayland'... 
conky: 'bunsen-wayland' wayland session running 'BunsenLabs' destop
DEBUG(0) [./src/display-wayland.cc:692]: conky: defining struts
```
</details>

<details>
<summary>config</summary>

```shell
-- BL-Boron-conky.conf

--[[
## Bunsenlabs User config files
## All default BunsenLabs user config files are located in /usr/share/bunsen/skel.
## The script bl-user-setup copies them to the user $HOME directory on first login.
## See more info with command 'bl-user-setup --help'
]]

--[[ conky configuration
 ------------------------------
 For conky variables and commands use the terminal command:

 man conky

 ------------------------------
 BunsenLabs conky threads

 Index Â» Scripts, Tutorials & Tips Â» Conky - Calendars / Clocks / Time
 https://forums.bunsenlabs.org/viewtopic.php?id=516

 Open a thread and post conky questions in: Index Â» GUI & Applications
 https://forums.bunsenlabs.org/viewforum.php?id=4

 Display your completed conky and codes
 Index Â» Scripts, Tutorials & Tips Â» Show us your conky
 https://forums.bunsenlabs.org/viewtopic.php?id=512

 ------------------------------
 BunsenLabs conky scripts help
 Openbox Menu/Preferences/Conky/Conky Manager Help

 If there are one or more conkys running, it is possible to kill one conky with
 the following command, IF you used what is between the quotes to start the conky, e.g.:
 pkill -xf "conky -q -c $HOME/.config/conky/BL-Default.conkyrc"
]]


conky.config = {

--  Window Settings
    own_window = true,
    own_window_type = 'desktop',
    own_window_transparent = true,
    own_window_hints = 'undecorated,below,skip_taskbar,skip_pager,sticky',
    own_window_colour = '000000',
    own_window_class = 'Conky',
    own_window_title = 'BunsenLabs Default Conky',

-- ARGB can be used for real transparency
--own_window_argb_visual = true, -- Options: true|false

-- NOTE that a composite manager is required for real transparency and ARGB will not
-- work as desired (in most cases) in conjunction with 'own_window_type override'.
-- Use with: own_window_type = 'normal',
-- Use with: own_window_transparent = false,

-- When ARGB visuals are enabled, use the following to modify the alpha value. Valid
-- range is 0-255, where 0 is 0% opacity, and 255 is 100% opacity.
--own_window_argb_value = 150,

    minimum_width = 260, minimum_height = 0,-- width | height
    maximum_width = 0,

    gap_x = 30,-- left | right2968
    gap_y = 10,-- up | down
    
--wayland or X
    out_to_x = false,
    out_to_wayland = true,

    alignment = 'top_left',
--  End Window Settings


--  Font Settings
-- Use Xft (anti-aliased font and stuff)
    use_xft = true,

--font = 'Liberation Mono:bold:size=10',
--font = 'Liberation Sans:size=10',
    font = 'Sans-serif:size=10',

-- Alpha of Xft font. Must be a value at or between 1 and 0
    xftalpha = 1,

-- Force UTF8? requires XFT
    override_utf8_locale = true,

    uppercase = false,
--  End Font Settings


--  Color Settings
    draw_shades = false,
    default_shade_color = '000000',

    draw_outline = false,-- amplifies text if true
    default_outline_color = '000000',

    default_color = 'ABB8B8',-- Boron Dark and Light foreground
--default_color = 'BECFCF',-- Dragon Dark foreground
--default_color = '4b8bad', -- Lithium blue
--default_color = '678b8b', -- Helium Beam green
--default_color = '656667', -- Waldorf original colour
--default_color = '7a7a7a', -- Flame  & BunsenLabs Grey
--default_color = '929292', -- BunsenLabs Grey
--default_color = 'C0C0C0', -- BunsenLabs Silver
    color0 = 'B0E0E6',-- PowderBlue
    color1 = '778899',-- LightSlateGray
    color2 = 'D8BFD8',-- Thistle
    color3 = '9ACD32',-- YellowGreen
    color4 = 'FFA07A',-- LightSalmon
    color5 = 'FFDEAD',-- NavajoWhite
    color6 = '00BFFF',-- DeepSkyBlue
    color7 = '5F9EA0',-- CadetBlue
    color8 = 'BDB76B',-- DarkKhaki
    color9 = 'C0C0C0',-- Silver
--  End Color Settings


--  Borders Section
    draw_borders = false,
-- Stippled borders?
    stippled_borders = 5,
-- border margins
    border_inner_margin = 5,
    border_outer_margin = 0,
-- border width
    border_width = 2,
-- graph borders
    draw_graph_borders = false,
--default_graph_height = 15,
--default_graph_width = 40,
--  End Borders Section


--  Miscellaneous Section
-- Boolean value, if true, Conky will be forked to background when started.
    background = true,

-- Adds spaces around certain objects to stop them from moving other things
-- around, this only helps if you are using a mono font
-- Options: right, left or none
    use_spacer = 'none',

-- Default and Minimum size is 256 - needs more for single commands that
-- "call" a lot of text IE: bash scripts
--text_buffer_size = 6144,

-- Subtract (file system) buffers from used memory?
    no_buffers = true,

-- change GiB to G and MiB to M
    short_units = true,

-- Imlib2 image cache size, in bytes. Default 4MiB Increase this value if you use
-- $image lots. Set to 0 to disable the image cache.
    imlib_cache_size = 0,

-- Use the Xdbe extension? (eliminates flicker)
-- It is highly recommended to use own window with this one
-- so double buffer won't be so big.
    double_buffer = true,

-- Maximum size of user text buffer, i.e. layout below TEXT line in config file
-- (default is 16384 bytes)
--max_user_text = 16384,

-- Desired output unit of all objects displaying a temperature. Parameters are
-- either "fahrenheit" or "celsius". The default unit is degree Celsius.
--temperature_unit = 'Fahrenheit',

-- Update interval in seconds
    update_interval = 1,

--  End Miscellaneous Section
};


conky.text = [[
S Y S T E M
${hr}
#Host:${alignr}${nodename}
#Uptime:${alignr}${uptime}
RAM:${alignr}${mem} / ${memmax}
# This version reports the same (incorrect) lower RAM usage as neofetch or htop:
#RAM:${alignr}${legacymem} / ${memmax}
#Swap usage:${alignr}${swap} / ${swapmax}
#Disk usage:${alignr}${fs_used /} / ${fs_size /}
#Root usage:${alignr}${fs_used /} / ${fs_size /}
#Home usage:${alignr}${fs_used /home} / ${fs_size /home}
CPU:${alignr}${cpu cpu0}%
#
# Weather information from weatherapi.com can be displayed in conky by
# using the script $HOME/.config/conky/scripts/bunsenweather-wapi.sh. The weatherapi
# service requires registration in order to receive an API Key, which has to be
# added to bunsenweather-wapi.sh. For further info see this script and the following thread:
# https://forums.bunsenlabs.org/viewtopic.php?id=2060
# 'owfont.ttf' is also required, from https://websygen.github.io/owfont/
# font licence: https://opensource.org/license/OFL-1.1
# Calling bunsenweather-wapi.sh from conky works by using
# ${execpi <t> /path/to/bunsenweather-wapi.sh "yourlocation"}
# where <t> is the update interval. If "yourlocation" is not defined, the script
# sets geolocation based on your IP adress using the website ipinfo.io.
#
#W E A T H E R
#${hr}
#${execpi 600 $HOME/.config/conky/scripts/bunsenweather-wapi.sh}

S H O R T C U T    K E Y S
${hr}
${execpi 600 $HOME/.config/conky/scripts/get_keybindings.sh}
]];
```
</details>

**Comment by Caellian** [comment] 2024-05-20 11:38
Possibly caused by changes from #1841.

Can you try running c51fbe66f63b365dcf4918a6d282c4a6af42225d (or [v1.20.1](https://github.com/brndnmtthws/conky/releases/tag/v1.20.1)) and see whether that version works?

I won't be able to debug this until later this week.

**Comment by magdesign** [comment] 2024-05-20 15:40
thanks for looking into this. can only test when its available in alpine edge... but hopefully someone else can!!

**Comment by berndf** [comment] 2024-06-04 09:55
I'm on gentoo using wayfire (based on wlroots) and here as well nothing is displayed on the wayland background in app-admin/conky-1.21.2. Pulling 1.20.1, it works again.

**Comment by Caellian** [comment] 2024-12-07 19:17
#2103 was merged. Can you verify whether this issue persists?

**Comment by Caellian** [comment] 2024-12-07 21:02
This seems to be the same issue as #1898.

Tested on hyprland, conky renders correctly using `wlr_layer_shell`, as [sway implements the same protocol](https://github.com/swaywm/sway/blob/master/protocols/wlr-layer-shell-unstable-v1.xml), I'm closing this.

Let me know and I'll reopen the issue if it isn't fixed.

**Closed** 2024-12-07 21:02 UTC
Labels: bug, display: wayland
