### ISSUE TITLE
Suggestion: adding processing options and logic via a shell script

### ISSUE THREAD

**Issue by john-walsh** [brndnmtthws/conky#438] opened 2017-12-09 22:16 UTC
Add an option in the config section, to send the conky 'text' section through bash/tsh/csh first, and then take the output of the shell and display it as the conky text.

eg:

conky.config = {
  pre_processes_script = 'bash'
}

conky.text = [[
echo 'hello via bash'
]]

If the shell context could be maintained over all executions (IDK if you can do that), then I would do it that way, or have it as an option.

This would give conky 'text' scripts access to variables, conditionals, string processing, much more system data...

**Comment by john-walsh** [comment] 2017-12-12 19:39
If the 'pre processing' script could be specified in the config (with path, if needed), then a user could also choose php, or any other script processors... Conky captures the output (like with php as a web page and apache) and uses that for it's display.

**Comment by su8** [comment] 2017-12-16 14:56
https://www.gnu.org/software/libc/manual/html_node/Pipe-to-a-Subprocess.html

**Comment by easysid** [comment] 2018-01-14 12:37
I am interested in knowing what is the use case for this? What can this do that cannot be done by the existing lua support?

**Comment by john-walsh** [comment] 2018-01-14 18:30
It gives access an any/all data available - not just what's in the predefined conky variables.

It gives you access to presistant variables.

It gives you access to logic control.

There are things I access with 'execi", and output that is conditional on various states, but it would be far easier to do it as a full bash script that then outputs the conky 'page', like a php web page would.

And if you could specify the 'external' processor (bash, php, ...), then you could have access to databases, ...

**Comment by lasers** [comment] 2018-09-07 01:56
9 months passed. What should we do with this issue today? Thanks.

**Comment by plikhari** [comment] 2018-09-07 04:20
We already have LUA as the embedded scripting language. 
You can refer to the [conkywx](https://foreverquest.blogspot.com/2018/03/conkywx-weather-ver-seven-build-333.html) - a weather program and the LUA widgets included to see the possibility. 

There is also a front end for mplayer - this uses pipes, shell, coreutil programs and LUA to show a smooth scrolling music player.

**Comment by john-walsh** [comment] 2018-09-20 00:34
Yes, I see the Lua support, so there is scripting support via that.

Thanks.

**Comment by plikhari** [comment] 2018-09-20 02:48
Yes - full scale LUA embedded.

**Comment by lasers** [comment] 2018-12-10 13:41
I'm going to close this because...
1) We have (some) lua support.
2) You can use `execp` / `execpi` instead.

    *# conky_config.conf*
    ```lua
    conky.config = {
        own_window = true,
        alignment = "middle_middle",
    }
    conky.text = [[
    ${execp /tmp/bash.sh}
    ${execp /tmp/python.py}
    ${execp /tmp/lua.lua}
    ]]
    ```

    *# script: /tmp/bash.sh*
    ```bash
    #!/usr/bin/env bash
    echo "hello via bash"
    ```
    *# script: /tmp/python.py*
    ```python
    #!/usr/bin/env python3
    print("hello via python")
    ```
    *# script: /tmp/lua.lua*
    ```lua
    #!/usr/bin/env lua
    print("hello via lua")
    ```

3) It wouldn't be trivial to implement this and even if somebody did, we would be breaking configs again. We have several issues that ought to be resolved first too. Some of them were caused by switching things around to make lua support possible (new config too). It is much easier to use `execp` / `execpi` instead. Your suggestion was appreciated. Keep them coming. Thank you.

**Closed by lasers** 2018-12-10 13:41 UTC
Labels: enhancement
