### ISSUE TITLE
[Bug]: `use_xft = true` breaks window sizing

### ISSUE THREAD

**Issue by simotek** [brndnmtthws/conky#1528] opened 2023-05-09 09:37 UTC
### What happened?

Window sizing is smaller when `use_xft = true` is set then when it is not, if a window is a forced size with min_width and max_width being the same then the window size will be slightly smaller then that.

This first image is with `use_xft=true` the colored temperature shape should be centered 
![shot-2023-05-09_18-54-42](https://user-images.githubusercontent.com/3827011/237056075-65368151-1bc5-43a1-82fd-a5ff2bcef135.jpg)

This second shot is showing everything working properly with it disabled
![shot-2023-05-09_18-55-23](https://user-images.githubusercontent.com/3827011/237056096-ca510c59-e5b0-44e4-af91-85863af497da.jpg)

Issue is seen running a few day old version of conky from git on openSUSE Tumbleweed

### Version

git

### Which OS/distro are you seeing the problem on?

Linux (other)

### Conky config

```Lua
https://github.com/philer/polycore  `/opt/conky/bin/conky -c  conkyrc.lua` I had to comment out line 45 of layout.lua to stop a crash as I don't have gpu support.
```

**Comment by Caellian** [comment] 2024-04-19 16:16
My guess was that font size (glyph width) gets used for window width calculation somehow, but that's not the case.

Closing for now as I can't reproduce (Openbox) with:
```
conky.config = {
  own_window = true,
  own_window_type = 'override',
  own_window_hints = 'undecorated,sticky,skip_taskbar,skip_pager',
  minimum_width = 500,
  maximum_width = 500,
  use_xft = true,
  font = 'Ubuntu:pixelsize=200',
}
conky.text = [[
  $conky_version
  $conky_version
  $conky_version
]]
```

Not sure if I'm missing something, but `use_xft` doesn't have any interaction with window size (besides making it larger if maximum_width not set).

Reopen the issue if you still have it and add which WM you're using.

**Comment by Caellian** [comment] 2024-04-20 19:24
I believe I found what causes this.

In configure event handler there's this:
```
int mw = surface->dpi_scale(maximum_width.get(*state));
if (text_width > mw && mw > 0) { text_width = mw; }
```
I don't think expected width in pixels should be affected by DPI. So even though it doesn't affect min_width, by affecting max_width it shrinks the window.

`surface->dpi_scale` is defined as:
```
int display_output_x11::dpi_scale(int value) {
#if defined(BUILD_XFT)
  if (use_xft.get(*state) && xft_dpi > 0) {
    return (value * xft_dpi + (value > 0 ? 48 : -48)) / 96;
  } else {
    return value;
  }
#else  /* defined(BUILD_XFT) */
  return value;
#endif /* defined(BUILD_XFT) */
}
```

There's a few things that might be improved:
- According to a comment on [this](https://stackoverflow.com/a/54511175/3837417) SO answer, conky should receive resize or move event if DPI changes while it's running.
  - Maybe conky starts on your system before DPI is set to a correct value.
  - That answer said we'd need to reopen temporary connections to the server in order to get up-to-date Xresources.
- According to [this](https://stackoverflow.com/a/70827735/3837417) SO answer, Xft dpi is a property that _has to be set somewhere correctly_ so it might be wrong.
  - It also includes a function for computing DPI manually.

**Comment by Caellian** [comment] 2024-04-30 20:22
Let me know if the issue needs to be reopened. I believe the linked PR fixes it.

**Closed** 2024-04-30 20:21 UTC
Labels: bug, display: x11, rendering

**Comment by Caellian** [comment] 2024-05-18 22:56
This is a game of whack-a-mole I swear.
