### ISSUE TITLE
Can't change window size without this hack

### ISSUE THREAD

**Issue by gsingh93** [brndnmtthws/conky#36] opened 2014-01-12 23:41 UTC
I have to use this hack to change the window size: http://obakfahad.com/conky-window-size-problem/

I shouldn't have to do this, minimum_size should work as intended.

**Comment by madworm** [comment] 2017-08-25 09:08
It would be nice to have this working.

**Comment by mswanson-me** [comment] 2018-02-26 21:47
Link in OP is broken. If this problem is still outstanding, please update the issue. For the time being, I have added the 'bug' label, but this issue still needs more detail before it can be addressed.

**Comment by gsingh93** [comment] 2018-02-27 00:29
I don't use conky anymore, but a quick search on archive.org shows the new site is: https://fahadahammed.com/conky-window-size-problem/

Seems like this is still a problem for other users though.

**Comment by lasers** [comment] 2018-08-05 13:56
I'm copying and pasting everything here.

## Conky Window Size Problem
_Posted on March 24, 2013 by Fahad Ahammed_



There is a common problem about conky window size . If you are using a huge conky then this problem will arise . Height of your conky will show problem . Conky window height will show as half or not full . Here i am giving an effective solution .

![conky-window-1](https://user-images.githubusercontent.com/852504/43686484-916e0384-988c-11e8-9a56-cf77529ff317.png)

This is the problem we face .

![conky-window-2](https://user-images.githubusercontent.com/852504/43686486-a39e59aa-988c-11e8-8326-b21df49f4130.png)
Make Sure your conky config files OWN WINDOW section is like mine .

**Also , make sure your**
```
minimum_size 1060 150
maximum_width 1060
```
**lines are adequate enough to show full window . Above “150” is used to set the vertical height .**

![conky-window-3](https://user-images.githubusercontent.com/852504/43686487-a3b94c42-988c-11e8-8616-2ebcf9b7683c.png)

Go to the start of “own_window_hints undecorate,sticky,skip_taskbar,skip_pager,below” and type “#” before this line like above and save the file .

![conky-window-4](https://user-images.githubusercontent.com/852504/43686488-a3ce301c-988c-11e8-80bf-c8b05060b0c5.png)

In the desktop you will see your conky like this , as a window which you can move and resize with mouse . Resize the window as you can resize any file manager window or applications by dragging the edge of that window .

![conky-window-5](https://user-images.githubusercontent.com/852504/43686489-a3e6c15e-988c-11e8-8b4b-73c2a912f63e.png)

Now you make sure your conky is visible fully by resizing like above picture .

![conky-window-6](https://user-images.githubusercontent.com/852504/43686490-a402bbac-988c-11e8-8634-1116384acbf8.png)

Now go to the text editor where you were editing the conky file and remove “#” and save the file .

![conky-window-7](https://user-images.githubusercontent.com/852504/43686491-a41837d4-988c-11e8-82a2-a96ad49d1b17.png)

Done ? 🙂


### Please let me know whether it is useful or not !!!
### Leave Comment .

**Comment by lasers** [comment] 2018-08-09 00:15
4 years 7 months passed. Can you determine if you're still having this problem today on `1.10.8` or preferably `1.10.9_pre` (git)? The older versions are not trustworthy due to too many changes that can be hard to track. Additionally, I'd like to see configs too so we know what variables are being used... and if we can reproduce this issue easily. Thank you.

**Comment by lasers** [comment] 2018-09-01 19:39
@su8 I found you too. I tested this with modified default config. I don't get this behavior.

@madworm You commented last year. Are you able to reproduce same thing this year?

**Comment by lasers** [comment] 2018-12-11 12:15
Few months ago, I tried this with modified default config. I couldn't reproduce this issue so I will go ahead and close this. Please reopen / comment back if you're still affected by this issue. Thanks.

**Closed by lasers** 2018-12-11 12:15 UTC
Labels: bug
