### ISSUE TITLE
Conky shows strange CPU Frequency (in MHz) data, seems number overlapping

### ISSUE THREAD

**Issue by RTX2022** [brndnmtthws/conky#1202] opened 2022-08-19 04:27 UTC
Issue

Conky always shows strange CPU Frequency (in MHz) , you can see the number always overlapped: 
![Screenshot from 2022-08-19 12-24-19](https://user-images.githubusercontent.com/111554010/185542586-8bb6f067-1ca6-43e3-ae02-c1ba03a6c792.png)

Does anyone know how to solve this problem? 

Information
Just use the default configuration file.

**Comment by clunkiersalt817** [comment] 2023-03-11 09:53
i think the issue is resolved so close this issue

**Comment by Caellian** [comment] 2024-04-12 20:00
Closing this as (under normal conditions), the text in conky seems to render fine in X11 (and ~Wayland).

If this issue persists for you, leave a comment and I'll re-open it. Just let me know whether you're running conky in Wayland or X11, and if it's X11, which `own_window_type`.

**Closed by Caellian** 2024-04-12 20:00 UTC
