### ISSUE TITLE
Conky overwrites itself after being moused-over

### ISSUE THREAD

**Issue by Kurtoid** [brndnmtthws/conky#156] opened 2015-10-15 22:10 UTC
Screenshot of bug: ![image](https://cloud.githubusercontent.com/assets/2405137/10528987/0ff06140-7368-11e5-94da-45f1e3321432.png)
All conky scripts work fine until the mouse moves over it while it is updating. Then the script just draws over itself, making it unusable.
Conky 1.9.0 compiled Mon Mar 23 17:14:33 UTC 2015 for Linux 3.2.0-77-generic (x86_64)

**Comment by Kurtoid** [comment] 2015-10-15 23:45
I found setting own_window_type to normal fixed it. I still think its a bug though because almost every script i can find is set to override, and it still works for nearly everyone else. I think this is an Ubuntu issue.

**Comment by dmknght** [comment] 2017-11-04 22:07
I am having same issue. Actually it happened because of using bot 'override' and 'transparent'. Sadly, override is the best choice. I found own_windows_type normal got disappeared after i went back to desktop (ctrl + D); and own_windows_type desktop disappeared after click on desktop.

**Comment by lasers** [comment] 2018-08-07 05:07
2 years 10 months passed. Can you determine if you're still having this problem today on `1.10.8` or `1.10.9_pre`? The older versions are not trustworthy. Do you still consider this a bug? Thanks.

**Comment by lasers** [comment] 2018-09-05 01:01
Can you try the current master? Thanks.

```bash
git clone https://github.com/brndnmtthws/conky
cd conky
mkdir -p build
cd build
cmake ..
make -j4  # 4 cores to run in parallel
src/conky -c ~/conky.conf # <-- your config goes here
```

**Comment by dmknght** [comment] 2018-09-05 01:17
I've tested with `override` option (right) with conky version `conky 1.10.8 compiled Tue May 15 07:41:15 UTC 2018 for Linux 4.9.0-6-amd64 x86_64` while 2 panels on the left is using `dock` 
![screenshot at 2018-09-05 08-15-36](https://user-images.githubusercontent.com/29118926/45065527-e4f31200-b0e3-11e8-9ee3-f71bbee62580.png)

**Comment by dmknght** [comment] 2018-09-05 01:46
I couldn't `make` current conky. Cmake gives me `lua not found` but i installed lua 5.3, lua 5.0, lua 5.2 for testing.
Anyway, i suggest replace `override` option by:
```
	own_window_type = 'dock',
	own_window_transparent = true,
	own_window_argb_visual = true,
	own_window_argb_value = 0,
```

**Comment by lasers** [comment] 2018-09-05 01:53
I can't find `lua not found`. Is this an error `Unable to find Lua 5.1.x`?

The code may be looking for `lua 5.1`.
```cmake
pkg_search_module(LUA REQUIRED lua5.1 lua-5.1 lua51 lua luajit)
```
In the commands above, try `cmake -DBUILD_LUA_CAIRO=ON -DBUILD_LUA_IMLIB2=ON -DBUILD_LUA_RSVG=ON ..` instead of `cmake ..`.

**Comment by lasers** [comment] 2018-09-05 02:00
Can you share your config too? I can't reproduce this issue with default config.

**Comment by dmknght** [comment] 2018-09-05 02:08
Sorry I forget that config file :p here is it.
[config.zip](https://github.com/brndnmtthws/conky/files/2350916/config.zip)

**Comment by lasers** [comment] 2018-09-05 02:11
```
conky: llua_load: cannot open /etc/conky/lua/clock.lua: No such file or directory
```
Where can I install `/etc/conky/lua/clock.lua`?

**Comment by lasers** [comment] 2018-09-05 02:13
Did you try installing `lua5.1 lua-5.1 lua51 lua luajit tolua++`?

**Comment by dmknght** [comment] 2018-09-05 02:49
No i didn't install them. I gave up.

**Comment by dmknght** [comment] 2018-09-05 03:16
Sorry i didn't notice that lua file. 
[lua.zip](https://github.com/brndnmtthws/conky/files/2351078/lua.zip)

**Comment by lasers** [comment] 2018-09-05 11:48
@dmknght FYI I have been using your config for more than an hour now. Working okay here.

**Comment by lasers** [comment] 2018-12-10 17:14
`Conky 1.11.0` came out few days ago. You can try that version or current master. 

Because I tested this three months ago and had confirmed this worked fine on current master for many hours (and that the initial issue was opened more than three years ago), I will go ahead and close this right away. Please reopen/comment back if you're still affected. Thank you.

**Closed by lasers** 2018-12-10 17:14 UTC
