### ISSUE TITLE
[Bug]: conky-1.20.0 hangs with no output. Debugging shows "X cursor Error".

### ISSUE THREAD

**Issue by stefantalpalaru** [brndnmtthws/conky#1833] opened 2024-04-17 14:04 UTC
### What happened?

After upgrading, conky stops working. Running it with "-D" produces a continuous list of errors:

```text
DEBUG(0) [/var/tmp/portage/app-admin/conky-1.20.0/work/conky-1.20.0/src/x11.cc:301]: X cursor Error:
Display: 5617b085b170, XID: 0, Serial: 489192
error code: [major: 131, minor: 59]
DEBUG(0) [/var/tmp/portage/app-admin/conky-1.20.0/work/conky-1.20.0/src/x11.cc:301]: X cursor Error:
Display: 5617b085b170, XID: 0, Serial: 489193
error code: [major: 131, minor: 59]
DEBUG(0) [/var/tmp/portage/app-admin/conky-1.20.0/work/conky-1.20.0/src/x11.cc:301]: X cursor Error:
Display: 5617b085b170, XID: 0, Serial: 489194
error code: [major: 131, minor: 59]
DEBUG(0) [/var/tmp/portage/app-admin/conky-1.20.0/work/conky-1.20.0/src/x11.cc:301]: X cursor Error:
Display: 5617b085b170, XID: 0, Serial: 489195
error code: [major: 131, minor: 59]
```

### Version

1.20.0

### Which OS/distro are you seeing the problem on?

Gentoo

### Conky config

```Lua
own_window = true,
	own_window_type = 'desktop',
```

**Comment by Caellian** [comment] 2024-04-17 18:50
Minor opcode indicates error with `X_XIGetProperty`.

**Comment by Caellian** [comment] 2024-04-17 19:22
@stefantalpalaru Do you mind building from [`fix/relative-valuator-override-missing-atom`](https://github.com/brndnmtthws/conky/tree/fix/relative-valuator-override-missing-atom) branch to confirm if the issue is fixed?

I'm pretty sure that should fix it, but confirmation would be appreciated.

**Comment by stefantalpalaru** [comment] 2024-04-17 19:30
I tested that branch and it does fix the problem.

**Comment by Caellian** [comment] 2024-04-17 19:40
Merged.

**Closed** 2024-04-17 19:40 UTC
Labels: bug, backend: x11, mouse events
