### ISSUE TITLE
exec doesn't run on first iteration

### ISSUE THREAD

**Issue by miseran** [brndnmtthws/conky#112] opened 2015-07-11 11:12 UTC
Since the update to 1.10.0, the exec command and friends don't run on the very first iteration for me.

For example, with the following config file

```
conky.config = {
    background = false,
    out_to_console = true,
    out_to_x = false,
    update_interval = 1.0,
    total_run_times = 0,
};

conky.text = [[
==${exec echo exec}==${execi 5 echo execi}==${texeci 5 echo texeci}==
]];
```

I get the output

```
========
==exec==execi==texeci==
==exec==execi==texeci==
==exec==execi==texeci==
```

etc.

**Comment by willemw12** [comment] 2015-09-19 09:42
Even worse, in cases where conky is only run once:

    total_run_times = 1

(e.g. the display-loop is executed by a containing program), there is no output at all.

**Comment by cju** [comment] 2015-10-01 13:47
I can confirm this behaviour also for use-cases where conky's output is piped into a bar like dzen. There, when restarting/reloading conky, the old/original output of the {t}exec{i} sequences is still being displayed…

**Comment by madhat2r** [comment] 2015-10-05 17:47
I am also having this issue...

**Comment by labichn** [comment] 2015-11-09 21:38
I can also confirm this issue. This bug prevents a number of simple use cases: a volume bar popup, for example, should be a single execbar iteration (total_run_times=1) with a duration of a second or so (update_interval=1). To get the same behavior (because of this bug) you need a very tight update interval with a large number of iterations so the initial empty bar isn't visible. I dug into this a bit but lost track of the control-flow of the callback system.

**Comment by marcpayne** [comment] 2015-11-28 10:44
The callback for `exec` (and others) is registered *after* all callbacks are run for the first time. In case anyone wants to investigate further, I'll try to explain what happens.

Starting from `conky.cc`
```
update_text()
|
|--- generate_text()
     |
     |--- update_stuff() [defined in common.cc]
     |    |
     |    |--- conky::run_all_callbacks()
     |
     |--- generate_text_internal()
          |
          |--- (*obj->callbacks.print)(obj, p, p_max_size) [aka print_exec() in exec.cc]
               |
               |--- conky::register_cb<exec_cb>(1, true, obj->data.s)
```

Ok... in this case, the ultimate purpose of `conky::run_all_callbacks()` is to ensure that the `work()` function of each registered callback is called. However, the first call to `run_all_callbacks()` happens before `register_cb<exec_cb>`, so there is no `exec_cb` object whose `work()` function we can call.

I think we need some serious refactoring to make this work as intended. It isn't straightforward to move the `register_cb` call somewhere more appropriate, and calling `run_all_callbacks()` later does not work, afaict.

**Comment by chepioq** [comment] 2015-12-21 19:39
Hi marcpayne
Have you solve this problem ?

**Comment by marcpayne** [comment] 2015-12-22 01:16
No, unfortunately. I recently started training for a new job and have not had time to work on this issue. I will put in some time during the holidays and try to come up with a solution.

**Comment by marcpayne** [comment] 2015-12-28 19:17
I think I have a decent solution now. I decided to push the [changes](https://github.com/marcpayne/conky/commit/3cea35f0017447295d18803131bd03062372007c) to my repo, but not submit a pull request yet. If anyone here is willing to test, please do and let me know how it works for you. I'll be happy to help if needed.

One thing I mentioned in my commit message is that `texeci` sometimes works on the first update, and sometimes doesn't. I assume that the thread doesn't always have time to complete on my system before the first set of results gets printed. Your results may vary. At least the non-threaded versions of exec all work as they should!

**Comment by lasers** [comment] 2018-08-03 19:17
Closed by https://github.com/brndnmtthws/conky/pull/192. Thanks. :+1:

**Closed by lasers** 2018-08-03 19:17 UTC
