### ISSUE TITLE
[Bug]: color ignored on local, rendered on X11Forward

### ISSUE THREAD

**Issue by BETLOG** [brndnmtthws/conky#1560] opened 2023-06-02 04:40 UTC
[edit] improved screenshot and supplied .conf example. 

### What happened?

Specified color ranges for graphs do not render on locally invoked conky, but DO render when the same script is X11Forwarded  from another machine via `ssh -X <remote> conky`

### Version

conky 1.18.0 compiled 2023-02-20 for Linux x86_64

### Which OS/distro are you seeing the problem on?

Ubuntu

### Conky config

```
conky.config = {
    alignment = 'top_right',
    background = true,
    border_width = 1,
    cpu_avg_samples = 2,
    default_color = 'white',
    default_outline_color = 'white',
    default_shade_color = 'white',
      default_graph_height = 30,
--       default_graph_width 30,
    double_buffer = true,
    draw_borders = false,
    draw_graph_borders = true,
    draw_outline = false,
    draw_shades = false,
    extra_newline = false,
    font = 'DejaVu Sans Mono:size=20',
    gap_x = 10,
    gap_y = 70,
    minimum_height = 15,
    minimum_width = 300,
    net_avg_samples = 2,
    no_buffers = true,
    out_to_console = false,
    out_to_ncurses = false,
    out_to_stderr = false,
    out_to_x = true,
    own_window = true,
--     own_window_class = 'Conky',
--     own_window_type = 'desktop',
    own_window_type = 'normal',
    own_window_transparent = false,
--    own_window_transparent = true,
    own_window_hints = 'undecorated,sticky,skip_taskbar,skip_pager,below',
    show_graph_range = false,
    show_graph_scale = false,
    stippled_borders = 0,
    update_interval = 1.0,
    uppercase = false,
    use_spacer = 'none',
    use_xft = true
}
conky.text = [[
${color green}${nodename}${color} ${alignc}${color #44ffFF}CPU:${color}
${cpugraph cpu0 20,40 00FF00 FF0000 -t}${voffset -10}
]]


```
two on the left (ssh -X, rendering color):
`Linux betlognuc 5.15.0-71-generic #78-Ubuntu SMP Tue Apr 18 09:00:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
`Linux betlogbrick 5.19.0-42-generic #43-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 18 18:21:28 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

one on right (local, not rendering color) : `Linux betlogbeast 6.2.0-20-generic #20-Ubuntu SMP PREEMPT_DYNAMIC Thu Apr  6 07:48:48 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

![2023-06-03--21-25-22_betlogbeast_glxgears](https://github.com/brndnmtthws/conky/assets/12265451/3f0ddcdc-4795-4f95-8d38-7fb6397fd2ea)

**Comment by bi4k8** [comment] 2023-06-02 14:31
I can't reproduce this locally, in XWayland at least. The provided conky config shows a small graph with a very dark grey CPU bar, as I would expect for #222222. What do you see with this conkyrc locally, and what do you see running it over `ssh -X`?

In your screenshot, what conkyrc is being used, which instances are local and which are via `ssh -X`, and how does it specify the `${cpugraph}`?

**Comment by BETLOG** [comment] 2023-06-03 00:52
> I can't reproduce this locally, in XWayland at least.

Then it's only failing in  X11.

> The provided conky config shows a small graph

I isolated a relevant element from the conky shown in the screenshot. To keep things simple.

>What do you see with this conkyrc locally

The one failing: conky at right of screenshot

>and what do you see running it over `ssh -X`?

conky with color working: at left and middle of screenshot
 
> In your screenshot, what conkyrc is being used, which instances are local and which are via `ssh -X`, and how does it specify the `${cpugraph}`?

Again; the relevant info is present in the conky snippet provided.

The full conky is generared by bash, and I'm trying to avoid any topic distraction by posting it. Suffice it to say there is nothing special about how the color is defined; it's exactly like I have shown in the example. It should not be failing. But it is.

**Comment by BETLOG** [comment] 2023-08-08 22:57
Yep, also Kubuntu 23.04:
![2023-08-09--08-55-58_betlogbeast_InstagramGoogleChrome](https://github.com/brndnmtthws/conky/assets/12265451/f74d572f-7c15-44c6-8d54-def30eb8ae26)

**Comment by Caellian** [comment] 2024-04-17 10:39
Try the latest HEAD `${cpugraph cpu0 0000FF FF0000 -t}` works for me:
![image](https://github.com/brndnmtthws/conky/assets/4082795/881337be-007e-4464-8ccb-39c12b8a6068)

**Comment by vmagnin** [comment] 2024-04-17 14:33
> I have also noticed that problem on all my machines since I upgraded them from Kubuntu 22.10 to Kubuntu 23.04 (coming with conky 1.18.0).

Colors came back when I updated my system from Kubuntu 23.04 to 23.10 (conky 1.19.4).
Thanks

**Comment by Caellian** [comment] 2024-04-17 19:36
Closing this then. Reply if you need this issue reopened in future.

**Closed by Caellian** 2024-04-17 19:36 UTC
Labels: bug, backend: x11, backend: wayland
