### ISSUE TITLE
[Bug]: conky window not shown at all on Wayland

### ISSUE THREAD

**Issue by abkein** [brndnmtthws/conky#2086] opened 2024-11-21 16:48 UTC
### What happened?

Runnind on Arch, Hyprland, it loads and settings up fonts forever, no window is shown.

### Version

both `1.21.5-pre-20091470` (via pacman), `1.21.9-pre-9449818` (self-compiled)

### Which OS/distro are you seeing the problem on?

Arch Linux, Hyprland 0.45.2 built from branch  at commit 12f9a0d0b93f691d4d9923716557154d74777b0a

### Conky config

```Lua
Default config with

out_to_wayland = true,
out_to_x = false,
```
```


### Stack trace

_No response_

### Relevant log output

```Shell
conky -DD
DEBUG(0) [/usr/src/debug/conky/conky/src/conky.cc:1956]: reading contents from config file '/home/kein/.config/conky/conky.conf'
conky: drawing to single buffer
DEBUG(1) [/usr/src/debug/conky/conky/src/core.cc:2108]: no templates to replace
DEBUG(1) [/usr/src/debug/conky/conky/src/core.cc:2108]: no templates to replace
DEBUG(1) [/usr/src/debug/conky/conky/src/core.cc:714]: Adding $cpu for CPU 0
DEBUG(1) [/usr/src/debug/conky/conky/src/core.cc:728]: Adding $cpubar for CPU 0
DEBUG(0) [/usr/src/debug/conky/conky/src/display-output.cc:39]: HTTP display output disabled. Enable by recompiling with 'BUILD_HTTP' flag enabled.
conky: FOUND: console
conky: FOUND: ncurses
conky: FOUND: file
conky: FOUND: x11
conky: FOUND: wayland
DEBUG(1) [/usr/src/debug/conky/conky/src/display-output.cc:99]: Testing display output 'x11'... 
DEBUG(1) [/usr/src/debug/conky/conky/src/display-output.cc:99]: Testing display output 'wayland'... 
DEBUG(1) [/usr/src/debug/conky/conky/src/display-wayland.cc:251]: Wayland display output 'wayland' enabled in config.
DEBUG(1) [/usr/src/debug/conky/conky/src/display-output.cc:101]: Detected display output 'wayland'... 
DEBUG(1) [/usr/src/debug/conky/conky/src/fonts.cc:64]: setting up fonts
DEBUG(1) [/usr/src/debug/conky/conky/src/fonts.cc:84]: loading fonts
DEBUG(0) [/usr/src/debug/conky/conky/src/display-output.cc:109]: Initialized display output 'wayland'... 
DEBUG(1) [/usr/src/debug/conky/conky/src/display-output.cc:99]: Testing display output 'ncurses'... 
DEBUG(1) [/usr/src/debug/conky/conky/src/display-output.cc:99]: Testing display output 'console'... 
DEBUG(1) [/usr/src/debug/conky/conky/src/display-output.cc:99]: Testing display output 'file'... 
conky: '(null)' wayland session running 'Hyprland' desktop
DEBUG(1) [/usr/src/debug/conky/conky/src/fonts.cc:84]: loading fonts
DEBUG(1) [/usr/src/debug/conky/conky/src/fonts.cc:84]: loading fonts
DEBUG(0) [/usr/src/debug/conky/conky/src/display-wayland.cc:692]: conky: defining struts

DEBUG(1) [/usr/src/debug/conky/conky/src/fonts.cc:64]: setting up fonts
DEBUG(1) [/usr/src/debug/conky/conky/src/fonts.cc:84]: loading fonts
DEBUG(1) [/usr/src/debug/conky/conky/src/fonts.cc:84]: loading fonts
DEBUG(1) [/usr/src/debug/conky/conky/src/fonts.cc:64]: setting up fonts
DEBUG(1) [/usr/src/debug/conky/conky/src/fonts.cc:84]: loading fonts
DEBUG(1) [/usr/src/debug/conky/conky/src/fonts.cc:84]: loading fonts
DEBUG(1) [/usr/src/debug/conky/conky/src/fonts.cc:64]: setting up fonts
DEBUG(1) [/usr/src/debug/conky/conky/src/fonts.cc:84]: loading fonts
DEBUG(1) [/usr/src/debug/conky/conky/src/fonts.cc:84]: loading fonts
DEBUG(1) [/usr/src/debug/conky/conky/src/fonts.cc:64]: setting up fonts
DEBUG(1) [/usr/src/debug/conky/conky/src/fonts.cc:84]: loading fonts
DEBUG(1) [/usr/src/debug/conky/conky/src/fonts.cc:84]: loading fonts
DEBUG(1) [/usr/src/debug/conky/conky/src/fonts.cc:64]: setting up fonts
DEBUG(1) [/usr/src/debug/conky/conky/src/fonts.cc:84]: loading fonts
DEBUG(1) [/usr/src/debug/conky/conky/src/fonts.cc:84]: loading fonts
DEBUG(1) [/usr/src/debug/conky/conky/src/fonts.cc:64]: setting up fonts
DEBUG(1) [/usr/src/debug/conky/conky/src/fonts.cc:84]: loading fonts
DEBUG(1) [/usr/src/debug/conky/conky/src/fonts.cc:84]: loading fonts
DEBUG(1) [/usr/src/debug/conky/conky/src/fonts.cc:64]: setting up fonts
DEBUG(1) [/usr/src/debug/conky/conky/src/fonts.cc:84]: loading fonts
DEBUG(1) [/usr/src/debug/conky/conky/src/fonts.cc:84]: loading fonts
DEBUG(1) [/usr/src/debug/conky/conky/src/fonts.cc:64]: setting up fonts
DEBUG(1) [/usr/src/debug/conky/conky/src/fonts.cc:84]: loading fonts
DEBUG(1) [/usr/src/debug/conky/conky/src/fonts.cc:84]: loading fonts
```

**Comment by Caellian** [comment] 2024-11-22 09:53
Can confirm the issue.

The fonts thing is just spam due to how fonts are managed. The problem is that conky doesn't display anything. `hyprctl` reports that the window should be visible:
```
Window 5ef2019dbb90 -> ./src/conky:
	mapped: 1
	hidden: 0
	at: 2,28
	size: 956,1050
	workspace: 3 (3)
	floating: 0
	pseudo: 0
	monitor: 0
	class: kitty
	title: ./src/conky
	initialClass: kitty
	initialTitle: kitty
	pid: 687435
	xwayland: 0
	pinned: 0
	fullscreen: 0
	fullscreenClient: 0
	grouped: 0
	tags: 
	swallowing: 0
	focusHistoryID: 1
```

**Comment by Caellian** [comment] 2024-11-22 10:02
Closing as duplicate of #1960

**Closed by Caellian** 2024-11-22 10:02 UTC
Labels: bug, display: wayland, priority: severe
