### ISSUE TITLE
[SOLVED]:  Loading problem under Fedora 38

### ISSUE THREAD

**Issue by enigma131** [brndnmtthws/conky#1664] opened 2023-10-24 15:39 UTC
### What happened?

Nice tool, I use it since years ;)

I've upgraded Fedora from 37 to 38 .
Now I have loading problem  : conky: error while loading shared libraries: liblua-5.3.so: cannot open shared object file: No such file or directory
Lua version is 5.4.4, and as opposite of Fedora 37, I can't downgrade Lua.
How to solve the loading error ?
Need I recompile it or done a ticket at Fedora ?

source       : conky-1.19.2-1.fc38.src.rpm

Edit: I've post a ticket  : https://forums.fedoraforum.org/showthread.php?331363-Fedora-38-problem-with-conky

### Version

1.19.2

### Which OS/distro are you seeing the problem on?

Fedora

Fedora gives link here :
https://packages.fedoraproject.org/pkgs/conky/conky/

**Comment by ctrlcctrlv** [comment] 2023-11-01 17:03
this is a packaging issue, not a bug in conky.

does Fedora not separately package all the main Lua versions?

**Comment by enigma131** [comment] 2023-11-04 17:13
I don't know, i'll get no response there. I had try, earlier lua versions can't be loaded anymore for F38
I've done an up.

**Comment by ctrlcctrlv** [comment] 2023-11-06 03:39
> i'll get no response there

that sounds like a personal problem

**Comment by enigma131** [comment] 2023-11-06 15:50
You mean? You got it on Fedora 38 ?

**Comment by ernesto1** [comment] 2024-01-31 03:18
@enigma131 this packaging problem is now fixed in fedora 39.

the new problem we have is that the version of conky available in the fedora repository does not support wifi.  

Conky uses an old library to access wifi data from your system. This library is now [deprecated in fedora](https://fedoraproject.org/wiki/Changes/RemoveWirelessExtensions).

hence fedora packages conky without wireless support : ( since F37 (that i am aware of)

**Comment by Caellian** [comment] 2024-04-17 11:23
Created a new issue for BUILD_WLAN option and migration to mac80211/cfg80211.

Closing this as wontfix as it's a fedora packaging problem.

**Closed by Caellian** 2024-04-17 11:23 UTC
Labels: wontfix

**Comment by enigma131** [comment] 2024-04-22 18:35
I will install Fedora 39 soon because F38 willl be EOL next times. I don't use Wifi on that computer.

**Comment by enigma131** [comment] 2024-05-05 17:02
Upgraded to F39 and same problem. F39 live is working, very very strange. All packets are same, conky, lua and imlib2

**Comment by Caellian** [comment] 2024-05-08 15:53
@enigma131 you can try:
- reinstalling `dnf install conky-1.19.6-1.fc40 lua-5.4.6-5.fc40`
- installing [older Lua](https://bodhi.fedoraproject.org/updates/?search=lua-5.3&packages=lua) if there's no conflicts, with full package name: `dnf install lua-5.3.5-3.fc29`

If no of that works, [build conky from source](https://github.com/brndnmtthws/conky/wiki/Installation#compiling-from-source) as that will make conky link to the latest version (you have installed).

This is something you should report to conky-maintainers@fedoraproject.org as nothing in our build files requires older version of Lua to be used so it's entirely a packaging problem (or you're doing something wrong).

**Comment by Caellian** [comment] 2024-05-09 09:43
> remove lua will break 72 packets, so i did not apply.

Ok, don't break your system, haha. So you really need conky to link to latest lua-libs.

>Dernière vérification de l’expiration des métadonnées effectuée il y a 0:04:18 le jeu. 09 mai 2024 09:28:17.
Aucune correspondance pour le paramètre: lua-5.3.5-3.fc29
Erreur : Impossible de trouver une correspondance: lua-5.3.5-3.fc29

Can you give a short translation of the first line? I'm guessing (don't speak french) it's saying something along the lines of "can't verify dependency because it's marked as expired effective <time and date>".

> Building gives me a lot of error

Paste those errors here, they will be helpful for debugging what's wrong on your system. Also, if you haven't already, link this issue in the email (respond to your own with a link to this issue). Package maintainers would benefit from details on this issue.

I'm working on updating `libiw` to `netlink` [here](https://github.com/brndnmtthws/conky/pull/1879). That's 80% complete, but I'm a bit busy with life stuff atm.

**Comment by enigma131** [comment] 2024-05-09 11:45
In english :
LC_ALL=C sudo dnf install lua-5.3.5-3.fc29
Last metadata expiration check: 4:15:29 ago on Thu May  9 09:28:17 2024.
No match for argument: lua-5.3.5-3.fc29
Error: Unable to find a match: lua-5.3.5-3.fc29

**Comment by enigma131** [comment] 2024-05-12 10:40
I've finaly found the issue.
I had 2 instance of conky, one in /usr/bin/ and one in /usr/local/bin/
when i do conky, it's the one not updated in /usr/local/bin/ that is called..
I think its an Fedora upgrade issue, can you confirm ?

**Comment by Caellian** [comment] 2024-05-12 13:01
> I've finaly found the issue.
> I had 2 instance of conky, one in /usr/bin/ and one in /usr/local/bin/
> when i do conky, it's the one not updated in /usr/local/bin/ that is called..
> I think its an Fedora upgrade issue, can you confirm ?

Not necessarily, that could've happened if you manually compiled conky and then installed it through CMake. It's unlikely that the package was bad because (I think) installed files are removed automatically on uninstall (i.e. they use the same path), so even if two versions used a different binary path the previous binaries would've been uninstalled properly.

**Comment by enigma131** [comment] 2024-05-12 18:21
Ok, but other strange thing, when i remove the binary from /usr/local/bin/ conky will be not found. I have to copy the one from correct path (from updates) to /usr/local/bin/ . Other binarys from /usr/bin are found from terminal

**Comment by enigma131** [comment] 2024-05-13 08:21
I've finaly found the issue.
I had 2 instance of conky, one in /usr/bin/ and one in /usr/local/bin/
when i do conky, it's the one not updated in /usr/local/bin/ that is called..
I think its an Fedora upgrade issue, can you confirm ?

**Comment by enigma131** [comment] 2024-05-13 08:23
Definitly solved.
As binary in /usr/local/bin/ is not updated by Fedora but the path is set in priority in PATH environment variable, I've removed the binary in that place.

**Comment by Caellian** [comment] 2024-05-13 11:49
> I've finaly found the issue.
I had 2 instance of conky, one in /usr/bin/ and one in /usr/local/bin/
when i do conky, it's the one not updated in /usr/local/bin/ that is called..
I think its an Fedora upgrade issue, can you confirm ?

Responded to this from mobile but I can't see it now on PC, guess it didn't get sent.

It's not necessarily an upgrade issue, what might've happened was that you installed conky via CMake at some point which used a different install path.
I believe `dnf` removes old files and adds new ones if paths change between versions, but it's also unlikely that they've actually changed.

**Comment by enigma131** [comment] 2024-05-14 06:41
No dnf don't remove old path(s).
