### ISSUE TITLE
conky is downloading a picture everytime i change the workspace, how to prevent it?

### ISSUE THREAD

**Issue by freddii** [brndnmtthws/conky#718] opened 2018-12-21 22:20 UTC
conky should only download the picture once in an hour, but it always downloads the picture when i switch from one workspace to another.

conky.config = {
update_interval=3600,
...

conky.text = [[
${font}BERLIN TV TOWER${hr 2}
${execi 3600 curl -o /tmp/cam1.jpg https://tv-turm.de/fileadmin/webcam/images.jpg}
${image /tmp/cam1.jpg -p 0,20 -s 320x240}
]]

i am using conky 1.10.8 compiled Wed Feb 28 17:11:42 UTC 2018 for Linux 4.4.0-101-generic x86_64

**Comment by plikhari** [comment] 2018-12-22 00:45
you are running an external command / process - you need to use `execpi` in place of `execi`

**Comment by freddii** [comment] 2018-12-22 04:59
That does not fix it. Still downloading the image when switching the workspace.

**Comment by freddii** [comment] 2018-12-22 06:47
![switching_workspace](https://user-images.githubusercontent.com/7213207/50371562-ab281780-05bd-11e9-8d5e-958cac1f77ba.gif)
just from workspace0 to workspace1 and back. Always same user on XFCE.

**Comment by lasers** [comment] 2018-12-22 06:48
Similar to #512

**Comment by freddii** [comment] 2018-12-22 07:01
the smal infobar at the bottom has a script with web request for the weather.
${execpi 3600 ./weather.sh}
but that one gets not triggered on workspace switch.

**Comment by lasers** [comment] 2018-12-22 08:05
Can you try the latest master?
```bash
git clone https://github.com/brndnmtthws/conky
cd conky
mkdir -p build
cd build
cmake ..
make -j4 # 4 cores to run in parallel
src/conky -c myconf.conf # <-- your config goes here
```
You also can try `conky -DD -c myconf.conf` in your terminal for more debugging. You probably should turn `background` off too for testing.

**Comment by freddii** [comment] 2018-12-22 09:05
i compiled and run it from github like explained.

The behaviour is the same.

**Comment by dbriba** [comment] 2018-12-22 18:30
try replace, in your conky,
background=true,
by 
background=false,

**Comment by freddii** [comment] 2018-12-22 18:35
yes already did that to see the logs.

**Comment by dbriba** [comment] 2018-12-24 05:04
I test your conky " https://github.com/freddii/conky/blob/master/freddii/image_view_cam " and for me no problem when I change the workspace.
I use KDE and my conky's version is  conky 1.10.8

`dominique@host-192-168-1-2 ~$ conky -v
conky 1.10.8_pre compiled Thu Jul 12 23:25:25 UTC 2018 for Linux 4.17.3-200.fc28.x86_64 x86_64

Compiled in features:

System config file: /etc/conky/conky.conf
Package library path: /usr/lib64/conky


 General:
  * math
  * hddtemp
  * portmon
  * IPv6
  * Curl
  * RSS
  * Weather (METAR)
  * Weather (XOAP)
  * wireless
  * support for IBM/Lenovo notebooks
  * old configuration syntax
  * Imlib2
  * apcupsd
  * iostats
  * Internationalization support
  * Debugging extensions

 Lua bindings:
  * Cairo
  * Imlib2
 X11:
  * Xdamage extension
  * Xinerama extension (virtual display)
  * Xshape extension (click through)
  * XDBE (double buffer extension)
  * Xft
  * ARGB visual
  * Own window

 Music detection:
  * MPD

 Default values:
  * Netdevice: eth0
  * Local configfile: $HOME/.conkyrc
  * Localedir: /usr/share/locale
  * Maximum netdevices: 64
  * Maximum text size: 16384
  * Size text buffer: 256
dominique@host-192-168-1-2 ~$ 
`

**Comment by dbriba** [comment] 2018-12-24 17:33
How do you launch conky when starting your session ?
With a script or by console ?
If it's with a script, can you show us ?

**Comment by freddii** [comment] 2018-12-24 18:31
By console

**Comment by dbriba** [comment] 2018-12-26 05:32
And what is the command line in your console ?

**Comment by lasers** [comment] 2018-12-26 06:14
@dbriba You tried KDE. It worked fine. I tried i3wm. It worked fine. I think it had to be on XFCE.

**Comment by dbriba** [comment] 2018-12-27 05:41
I can confirm that.
On my PC I have two DE, kde and xfce (I use xfce if my kde don't work).
When I am on xfce I have same problem with this conky, it reload image when I change workspace.

**Comment by lasers** [comment] 2019-02-25 21:32
@freddii Can you try #789? It might be the bugfix.

**Comment by lasers** [comment] 2019-02-26 00:45
Cannot reproduce this on minimal xfce4 on latest master nor `1.10.8`. Will wait for you.

**Comment by freddii** [comment] 2019-02-26 01:13
i can not reproduce the bug on xfce with conkys latest master.
Seams #789 fixed it.

**Comment by lasers** [comment] 2019-02-26 01:16
Can you `git checkout v1.10.8` and recompile again to confirm that it's still causing issue? If yes, then we can do git bisect next to find the right commit that fixes it.

**Comment by freddii** [comment] 2019-02-26 01:22
git checkout v1.10.8 is still causing the issue.

**Comment by lasers** [comment] 2019-02-26 01:28
Okay. Do you know how to `git bisect`? It's easy. https://git-scm.com/docs/git-bisect

Something like this...
* `git bisect start` 
* `git checkout master` <-- this part might be done already
* `git bisect bad`  <-- we have to do this opposite to find the good commit instead of bad commit
* `git checkout v1.10.8` 
* `git bisect good` <--- 

Then it should start checking you out in random places. You have to keep recompiling again and again and again... narrowing it down to either #789 or some other commit.

Because of opposite `good` vs `bad`, you have to remember this.
* If it is still broken, mark it good.
* If it is working okay, mark it bad.

**Comment by freddii** [comment] 2019-02-26 01:52
conky$ git bisect good
389314699520fa38141626ecf107dee1d4fdd901 is the first bad commit
commit 389314699520fa38141626ecf107dee1d4fdd901
Author: Monsterovich <monsterovich@gmail.com>
Date:   Sun Feb 24 16:45:48 2019 +0200

    Added option to disable redraw on desktop change

:040000 040000 f11bacea44ca84a48392afd26893d23395e6d157 1c3a5388a099deadd58a01ac97d29252673dd368 M	extras
:040000 040000 c67ff53febb920fde5f9a87adba5c920f6e178e2 772727e896205f575fe3b9169ab05e0e63cf2626 M	src

**Comment by lasers** [comment] 2019-02-26 01:55
Thank you very much for confirming the commit that fixed your bug. It was #789 after all. Closing. :+1:

**Closed by lasers** 2019-02-26 01:55 UTC
Labels: bug
