### ISSUE TITLE
Not accurate RAM memory usage

### ISSUE THREAD

**Issue by morfikov** [brndnmtthws/conky#995] opened 2020-08-16 16:49 UTC
Recently, there was a `conky` update in Debian (sid):

`conky (1.11.6-1) over (1.10.8-1.1) ...`

With the new version, I noticed that the RAM utilization is different compared to what was in the previous version. Take a look at the following picture:

![2020-08-16-03:09:56](https://user-images.githubusercontent.com/3797768/90339319-84fb8a80-dfdf-11ea-8b17-4ec1337c5e3f.png)

So `free` shows `816M` used, but conky 1,2G.

At first, I though about the `no_buffers` option, but it's set as usual to `true` . 

So why does `conky` show different RAM usage compared to `free` ?

**Comment by ElArtista** [comment] 2020-08-20 21:33
Same here, conky shows increased RAM usage (by about 260MB)

**Comment by stevenxxiu** [comment] 2020-09-09 08:21
Same here on the lastest `master` commit.

**Comment by frc-kde** [comment] 2020-10-14 18:59
Same here in openSUSE Tumbleweed, Debian testing, Fedora 32, Mageia 8 beta, and Void Linux, as each one upgraded to Conky 1.11.6.

All of them ─ except Debian testing ─ previously presented another issue, such as "Negative or Very Low RAM Memory Usage".

Arch Linux still presents "Negative or Very Low RAM Memory Usage", but didn't upgrade to Conky 1.11.6, yet.

The first distro I have seen presenting "Negative or Very Low RAM Memory Usage" was PCLinuxOS, back in August 2019, but its team worked to fix it, and it didn't happen again.

https://www.pclinuxos.com/forum/index.php/topic,149427.msg1279912.html

They referred to #877, back then.

But I have seen many other Issues, here, related to the same things ─ "Negative or Very Low RAM usage" ─ and "Very High RAM usage", and now I will try to read (_and list_) all of them, from here back to #877, trying to understand all I can.

By now, all I can say is that, back in December 2018 / January 2019, Conky presented the same values as **htop** ─ while **free** and **top** presented a few less ─ at least in KDE Neon and Sabayon:

```
RAM         Used      Free    Buffer     Cache   Buff/Cache   Available    (used Swap)

Conky   2.4  GiB   828 MiB   101 MiB   794 MiB                1.43 GiB   278 MiB
Htop    2.4  GiB                                                         278 MiB
Top     2150 MiB   830 MiB                          944 MiB   1243 MiB   278 MiB
Free    2.1  GiB   829 MiB                          943 MiB   1.2  GiB   277 MiB
```

Now, I see that things are not so simple, in other distros ─ but **free** and **top** still show a few less RAM usage than **htop** and **Conky**, even for distros with previous Conky's versions.

**Comment by taigrr** [comment] 2020-10-31 07:16
My instance shows over 1GB difference, 4.9 (actual) vs 5.6 (conky)

**Comment by taigrr** [comment] 2020-10-31 07:16
My instance shows nearly 1GB difference, 4.9 (actual) vs 5.6 (conky)

**Comment by frc-kde** [comment] 2020-11-06 21:00
![Linux-distros-RAM-usage-startup-Graph_2020-10-Conky](https://user-images.githubusercontent.com/72884301/98413661-c3da3300-2058-11eb-9682-4bd84e05ba14.jpg)

Same here, in openSUSE Tumbleweed, Fedora, Mageia 8 (_beta_), Debian testing and Void, after July 2020 ─ but I have finally understood it is not an isue. ─ It is just a new and more acurate way to calculate "Mem used", [proposed / subscribed by Linus Torwalds back in 2014](https://github.com/torvalds/linux/commit/34e431b0ae398fc54ea69ff85ec700722c9da773) (_Kernel 3.14_).

It has been proposed to Conky back in [June 2019](https://github.com/brndnmtthws/conky/pull/859) and applied in [October 2019](https://github.com/brndnmtthws/conky/commit/11695b076abf72d797879c7c3b16fe89f3b68ca9), about 10 months before Conky 1.11.6 landed to my rolling release distros and Fedora.

I am not an expert, and maybe I am wrong. ─ That is what I guess I have understood.

**Comment by nihilix-melix** [comment] 2020-11-07 13:28
I've made a pull request #1028 for conky to have the same output than free.

**Comment by chromer030** [comment] 2021-01-18 08:19
The issue persists yet in Arch Linux , returns incorrect value for used RAM compared to htop and free -h.

kernel : 5.10.7

**Comment by ChrisCheney** [comment] 2021-04-22 06:00
I just found this issue after opening regression #1090 about the breakage the change in this issue caused. This issue # was left out of the commit.

'free' and 'top' apparently intentionally did not change due to backwards compatibility reasons, but added the available field. The data they report for 'used' is off by **very a LARGE margin** and can lead to out of memory issues if actually relied on.

htop, inxi, neofetch and screenfetch have all been corrected to report the information correctly, some in git and some in released versions. Conky also reported usage correctly until this mass delusion was implemented. Now there appears to be no way except by using 'exec' to get the correct info in Conky either.

As an example see the reporting difference between Conky and actual usage on my system 7.75GiB vs 15.20GiB:

![Screenshot from 2021-04-22 00-38-06](https://user-images.githubusercontent.com/5958984/115662505-b19d3a00-a304-11eb-80dc-d4ddd3c37bff.png)

The top line is running exec MemTotal-MemAvailable to get the correct information.

**Comment by brndnmtthws** [comment] 2021-04-24 16:04
I'm going to close this. Conky (going forward) will report memory usage (with the `$mem` var) as `MemTotal - MemAvailable`, and provides `$legacymem` for those who want the old behaviour.

See https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=34e431b0ae398fc54ea69ff85ec700722c9da773 for details on how `MemAvailable` is calculated.

Fixed in #1092.

**Closed by brndnmtthws** 2021-04-24 16:04 UTC

**Comment by beyond9thousand** [comment] 2022-02-25 22:59
@brndnmtthws i am a bit confused though, why is $mem an option if it reports the incorrect memory usage? or am i unable to grasp something crucial here?

**Comment by taigrr** [comment] 2022-02-25 23:13
@beyond9thousand [this is why](https://xkcd.com/1172/). :)

**Comment by frc-kde** [comment] 2022-02-26 02:44
Now, I am using to show "RAM usage" from all main tools:

```Mem:               ${alignr 100}up  ${uptime}

Total - Available  ${alignr 100}${exec bash MemInfo.sh; cat MemInfo.txt}
Conky (Mem)        ${alignr 100}${mem}
free               ${alignr 100}${exec free -m | grep Mem | cut -c 25-35} MiB
top                ${alignr 100}${exec top -E m -b -n 1  | grep buff | cut -c 41-50} MiB
neofetch           ${alignr 100}${exec neofetch  --stdout | grep -o -P '.{0,0}Memory.{0,9}' | cut -b 8-12} MiB
htop               ${alignr 100}${exec export TERM=xterm; echo q | htop | aha --line-fix | html2text | grep -o -P '.{0,6}/15' | cut -b 1-6}iB
# inxi               ${alignr 100}${exec inxi --memory-short | grep -o -P '.{0,0}used.{0,14}' | cut -b 6-14}
screenfetch        ${alignr 100}${exec screenfetch -n -N | grep -o -P '.{0,0}RAM.{0,9}' | cut -b 5-12}```

**Comment by beyond9thousand** [comment] 2022-03-02 22:23
@frc-kde can you explain what have you done here? i am a little lost. just need to fix the ram usage in my conky, currently looks like this
 
```
conky.config = {
	background = true,
	use_xft = true,
	font = '123:size=9',
	xftalpha = .005,
	update_interval = 1.5,
	total_run_times = 0,
	own_window = true,
	own_window_type = 'normal',
	own_window_transparent = true,
	own_window_class = 'conky-semi',
	own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
	own_window_argb_visual = true,
	own_window_argb_value = 0,
	double_buffer = true,
	minimum_width = 240, minimum_height = 5,
	maximum_width = 400,
	draw_shades = false,
	draw_outline = false,
	draw_borders = false,
	draw_graph_borders = true,
	default_color = 'gray',
	default_shade_color = 'red',
	default_outline_color = 'white',
	alignment = 'bottom_left',

	gap_x = 7,
	gap_y = 7,

	stippled_borders = 3,
	border_inner_margin = 4,
	border_width = 5,

	no_buffers = true,
	uppercase = false,
	cpu_avg_samples = 2,
	net_avg_samples = 1,
--override_utf8_locale yes
	use_spacer = 'right',
	text_buffer_size = 256,

};

conky.text = [[
${font Arial:bold:size=10}${color #ab7c15}${color #ab7c15}beyond9thousand ${color #ab7c15} ${hr 1}
$font${color #909090}$sysname $kernel $alignr $machine
Uptime $alignr${uptime_short}
#${font Arial:bold:size=10}${color #ab7c15}NETWORK ${color #ab7c15}${hr 1}
##$font${color #909090}IP on wlo1 $alignr ${addr wlo1}
#$font${color #909090}Up $alignr ${upspeed wlo1}
#${color #909090}${upspeedgraph wlo1 20,250 #909090 #909090}
#${color #909090}Down $alignr ${downspeed wlo1}
#${color #909090}${downspeedgraph wlo1 20,250 #909090 #909090}
#${color #909090}Uploaded: $alignr ${totalup wlo1} Downloaded: $alignr ${totaldown wlo1}

${font Arial:bold:size=10}${color #ab7c15}Processor ${color #ab7c15}${hr 1}
$font${color #909090}${cpu cpu0}%
$font${color #909090}${cpubar cpu0}
CPU Frequency $alignr${freq 0}MHz
CPU Temperature $alignr${hwmon 4 temp 1}°C

${font Arial:bold:size=10}${color #ab7c15}Memory ${color #ab7c15}${hr 1}
$font${color #909090}$legacymem / $memmax $alignr $memperc%
$membar

${font Arial:bold:size=10}${color #ab7c15}NVMe SSD ${color #ab7c15}${hr 1}
$font${color #909090}${fs_used /home} / ${fs_size /home} $alignr Free: ${fs_free /home}
${fs_bar /home}
${font Arial:bold:size=10}${color #ab7c15}Disk I/O ${hr 1}
$font${color #909090}Read:$font $alignr$diskio_read
${color #909090}${diskiograph_read 20,250 #909090 #909090 750}
${color #909090}Write: $font $alignr$diskio_write
${color #909090}${diskiograph_write 20,250 #909090 #909090 750}

${font Arial:bold:size=10}${color #ab7c15}Processes ${color #ab7c15}${hr 1}
$font${color #ab7c15}Total: ${color}$alignr${processes}
${color #909090}$font${top_mem name 1}${alignr}${top_mem mem 1} %
$font${top_mem name 2}${alignr}${top_mem mem 2} %
$font${top_mem name 3}${alignr}${top_mem mem 3} %
$font${top_mem name 4}${alignr}${top_mem mem 4} %
$font${top_mem name 5}${alignr}${top_mem mem 5} %
]];
```

![image](https://user-images.githubusercontent.com/77363063/156459888-84e2816e-2fbe-45db-aa32-54d283aa21ed.png)

**Comment by frc-kde** [comment] 2022-03-03 01:29
@beyond9thousand

> $font${color #909090}$legacymem / $memmax $alignr $memperc%
> $membar

I think `membar` and `memperc` are related to `mem`, while `legacymem` shows what `free` tool would show instead.

Here an experiment I have done just now:

![2022-03-02_22-12-56_Pc](https://user-images.githubusercontent.com/72884301/156477165-df527522-f25f-4c05-865a-92ca4395cb9f.jpg)

At left, above:
```
Mem  ${alignr}${mem} / ${memmax}  ${alignr}${membar 6,90}
Legacy  ${alignr}${legacymem} / ${memmax}                  ${alignr}$memperc%
Swap ${alignr}${swap} / ${swapmax}  ${alignr}${swapbar 6,90}
```
At right, above:
```
Mem:               ${alignr 100}up  ${uptime}

Total - Available  ${alignr 100}${exec bash MemInfo.sh; cat MemInfo.txt}
Conky (Mem)        ${alignr 100}${mem}
Conky (LegacyMem)  ${alignr 100}${legacymem}
free               ${alignr 100}${exec free -m | grep Mem | cut -c 25-35} MiB
top                ${alignr 100}${exec top -E m -b -n 1  | grep buff | cut -c 41-50} MiB
neofetch           ${alignr 100}${exec neofetch  --stdout                                              | grep -o -P '.{0,0}Memory.{0,9}' | cut -b 8-12} MiB
# htop               ${alignr 100}${exec export TERM=xterm; echo q | htop | aha --line-fix | html2text | grep -o -P '.{0,6}/15' | cut -b 1-6}iB
inxi               ${alignr 100}${exec inxi --memory-short                                             | grep -o -P '.{0,0}used.{0,14}' | cut -b 6-14}
screenfetch        ${alignr 100}${exec screenfetch -n -N                                               | grep -o -P '.{0,0}RAM.{0,9}' | cut -b 5-12}
```
Note that "14%" is a cut of "14.7%", which corresponds to `mem / memmax`, is to say the percentual of "2.28 / 15.5".

The `legacymem` is a lonely object, just for who wants to keep consistency with old Conky versions. -- There is no `legacymemperc` to give me "9.3%" in my example.

**Comment by beyond9thousand** [comment] 2022-03-04 06:56
is there no way in which i would be able to produce the same visual result but with accurate membar and memperc? (similar to legacymem's output)

**Comment by beyond9thousand** [comment] 2022-03-04 07:00
@frc-kde 

is there no way in which i would be able to produce the same visual result but with accurate membar and memperc? (similar to legacymem's output)

**Comment by ChrisCheney** [comment] 2022-03-04 08:24
> Total - Available  ${alignr 100}${exec bash MemInfo.sh; cat MemInfo.txt}
> Conky (Mem)        ${alignr 100}${mem}
> free               ${alignr 100}${exec free -m | grep Mem | cut -c 25-35} MiB
> top                ${alignr 100}${exec top -E m -b -n 1  | grep buff | cut -c 41-50} MiB
> neofetch           ${alignr 100}${exec neofetch  --stdout | grep -o -P '.{0,0}Memory.{0,9}' | cut -b 8-12} MiB
> htop               ${alignr 100}${exec export TERM=xterm; echo q | htop | aha --line-fix | html2text | grep -o -P '.{0,6}/15' | cut -b 1-6}iB
> inxi               ${alignr 100}${exec inxi --memory-short | grep -o -P '.{0,0}used.{0,14}' | cut -b 6-14}
> screenfetch        ${alignr 100}${exec screenfetch -n -N | grep -o -P '.{0,0}RAM.{0,9}' | cut -b 5-12}

Total - Available is the correct way to report memory under Linux 3.14+

conky, inxi, screenfetch all report "Total - Available"
neofetch does as well but only in git and it has not had a new release in nearly 2 years seems dead-ish

free, top report legacy information due to backwards compatibility reasons the xkcd link @taigrr referenced, but also report the "new" 2014 available memory amount

htop seems to be buggy due to previous reporters not understanding reporting with available makes a huge difference and that the old way is borderline useless on modern system. At the moment htop reports my system is only using half what it actually is 8GB vs 15GB.  I'll file a bug report about it.

**Comment by frc-kde** [comment] 2022-03-04 11:04
> is there no way in which i would be able to produce the same visual result but with accurate membar and memperc? (similar to legacymem's output)

`mem`, `membar` and `memperc` are accurate.

`legacymem` is **not** accurate

**Comment by frc-kde** [comment] 2022-03-04 12:03
> conky, inxi, screenfetch all report "Total - Available" neofetch does as well but only in git and it has not had a new release in nearly 2 years seems dead-ish
> 
> free, top report legacy information due to backwards compatibility reasons the xkcd link @taigrr referenced, but also report the "new" 2014 available memory amount
> 
> htop seems to be buggy due to previous reporters not understanding reporting with available makes a huge difference and that the old way is borderline useless on modern system. At the moment htop reports my system is only using half what it actually is 8GB vs 15GB. I'll file a bug report about it.

Unhappily, things are not so simple in real life, as different distros use different versions of these tools.

KDE Neon (_'buntu 20.04_) still uses old Conky and inxi versions. Ok, it will change next months.

htop 3.1.0 has shown correct "Total - Available", as I could see in openSUSE Tumbleweed, Void, Manjaro, back in October 2021. But now, htop 3.1.2 doesn't do it anymore.

Neofetch now shows correct "Total - Available", but only in MX Linux and Slackware 15. Maybe it has been fixed by the teams of these distros.

**Comment by beyond9thousand** [comment] 2022-03-18 04:57
> > is there no way in which i would be able to produce the same visual result but with accurate membar and memperc? (similar to legacymem's output)
> 
> `mem`, `membar` and `memperc` are accurate.
> 
> `legacymem` is **not** accurate

So ok, hear me out. When i have zero apps open, my ram usage is still going to be well over 3GB as opposed to 1.2-1.5 when i boot up my system? How does this work exactly?
