### ISSUE TITLE
[Bug]: 1.21.1 conky display is truncated

### ISSUE THREAD

**Issue by AngryPhantom** [brndnmtthws/conky#1931] opened 2024-05-22 15:10 UTC
### What happened?

Upgrading to conky 1.21.1-1 on Arch Linux makes it look truncated (not full):

![b](https://github.com/brndnmtthws/conky/assets/17167075/71bd24a4-6c39-4503-8995-2007a5bb58ee)

Downgraded to version 1.20.2 and now it's fine, as it should be:

![a](https://github.com/brndnmtthws/conky/assets/17167075/1a7f90b2-33fa-464c-bb26-efbc023655d4)

### Version

1.21.1-1

### Which OS/distro are you seeing the problem on?

Arch Linux

### Conky config

```Lua
conky.config = {
	alignment = 'bottom_right',
	background = false,
	border_width = 1,
	border_inner_margin = 20,
	cpu_avg_samples = 2,
	net_avg_samples = 2,
	draw_borders = true,
	draw_shades = false,
	stippled_borders = 0,
	double_buffer = true,
	out_to_x = true,
	out_to_wayland = false,
	own_window = true,
	own_window_transparent = false,
	own_window_colour = '20253b',
	own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
	own_window_class = 'Conky',
	own_window_type = 'desktop',
	own_window_argb_visual = false,
	own_window_argb_value = 182,
	update_interval = 1.0,
	use_xft = true,
	font = "Terminus:size=10",
	gap_x = 60,
	gap_y = 80,
	minimum_height = 250,
	minimum_width = 250,
	default_color = 'a6a6a6',
	default_outline_color = 'a6a6a6',
	default_shade_color='a6a6a6',
}

conky.text = [[
${color a6a6a6}Uptime:$color ${alignr}$uptime

${color a6a6a6}RAM:$color $mem ${alignr}${memperc}%

${color a6a6a6}CPU:$color ${cpu cpu1}% ${cpubar 5}
${color a6a6a6}CPU:$color ${cpu cpu2}% ${cpubar 5}
${color a6a6a6}Temp:$color ${execi 60 sensors | grep 'CPU T' | cut -c22-28}

${color a6a6a6}GPU:$color ${execi 60 nvidia-settings -query [gpu:0]/GPUCoreTemp -t}°C

${color a6a6a6}Down:$color ${downspeedf wlan0} KB/s ${alignr}${totaldown wlan0}
${color a6a6a6}Sent:$color ${upspeedf wlan0} KB/s ${alignr}${totalup wlan0}

$hr

${color a6a6a6}Local IP:${color} ${alignr}${addr wlan0}

${color a6a6a6}Public IP:${color} ${alignr}${execi 10800 curl "https://ifconfig.me/"}
]]
```

**Comment by akyag** [comment] 2024-05-23 03:51
Same here 

![image](https://github.com/brndnmtthws/conky/assets/7376589/b5116e5b-10cb-4fba-8a69-f4dd8eccee0e)

I am on arch based distro and the latest conky version.

```
conky.config = {

	--Various settings
	background = true, 							-- forked to background
	cpu_avg_samples = 2,						-- The number of samples to average for CPU monitoring.
	diskio_avg_samples = 10,					-- The number of samples to average for disk I/O monitoring.
	double_buffer = true,						-- Use the Xdbe extension? (eliminates flicker)
	if_up_strictness = 'address',				-- how strict if testing interface is up - up, link or address
	net_avg_samples = 2,						-- The number of samples to average for net data
	no_buffers = true,							-- Subtract (file system) buffers from used memory?
	temperature_unit = 'celsius',				-- fahrenheit or celsius
	text_buffer_size = 2048,					-- size of buffer for display of content of large variables - default 256
	update_interval = 1,						-- update interval
	imlib_cache_size = 0,                       -- disable image cache to get a new spotify cover per song

	-- Placement (Conky on MIDDLE of THREE monitors at 1920x1080)
	--alignment = 'top_left',		                -- top_left,top_middle,top_right,bottom_left,bottom_middle,bottom_right,
	--gap_x = 3540,                               -- pixels between right or left border
	--gap_y = 70,									-- pixels between bottom or left border

    -- Placement (For SINGLE monitor users!)
	alignment = 'top_right',		            -- top_left,top_middle,top_right,bottom_left,bottom_middle,bottom_right,
	gap_x = 310,								-- pixels between right or left border
	gap_y = 580,								-- pixels between bottom or left border

    -- Size
    minimum_height = 210,						-- minimum height of window
	minimum_width = 240,						-- minimum width of window
	maximum_width = 260,						-- maximum width of window

	--Graphical
	border_inner_margin = 5, 					-- margin between border and text
	border_outer_margin = 5, 					-- margin between border and edge of window
	border_width = 0, 							-- border width in pixels
	default_bar_width = 260,					-- default is 0 - full width
	default_bar_height = 10,					-- default is 6
	default_gauge_height = 25,					-- default is 25
	default_gauge_width =40,					-- default is 40
	default_graph_height = 40,					-- default is 25
	default_graph_width = 153,					-- default is 0 - full width
	default_shade_color = '#000000',			-- default shading colour
	default_outline_color = '#000000',			-- default outline colour
	draw_borders = false,						-- draw borders around text
	draw_graph_borders = true,					-- draw borders around graphs
	draw_shades = false,						-- draw shades
	draw_outline = false,						-- draw outline
	stippled_borders = 0,						-- dashing the border

	--Textual
	format_human_readable = true,				-- KiB, MiB rather then number of bytes
	font  = 'SF Pro Text:size=10',  	-- the default font used
	font2 = 'SF Pro Display:size=10:bold',         	-- font for the time
	font3 = 'SF Pro Rounded:pixelsize=70',               	-- font for the date
	font4 = 'Inter:bold:size=12',              -- font for the keybindings heading
	font5 = 'FiraCode Nerd Font:size=18',	-- font for icons.
	max_text_width = 0,							-- 0 will make sure line does not get broken if width too smal
	max_user_text = 16384,						-- max text in conky default 16384
	override_utf8_locale = true,				-- force UTF8 requires xft
	short_units = true,							-- shorten units from KiB to k
	top_name_width = 21,						-- width for $top name value default 15
	top_name_verbose = false,					-- If true, top name shows the full command line of  each  process - Default value is false.
	uppercase = false,							-- uppercase or not
	use_spacer = 'none',						-- adds spaces around certain objects to align - default none
	use_xft = true,								-- xft font - anti-aliased font
	xftalpha = 1,								-- alpha of the xft font - between 0-1

	--Windows
	own_window = true,							-- create your own window to draw
	own_window_argb_value = 180,			    -- real transparency - composite manager required 0-255
	own_window_argb_visual = true,				-- use ARGB - composite manager required
	own_window_class = 'Conky',					-- manually set the WM_CLASS name for use with xprop
	own_window_colour = '#1e1e2e',				-- set colour if own_window_transparent no
	own_window_transparent = false,				-- if own_window_argb_visual is true sets background opacity 0%
	own_window_title = 'conky',			-- set the name manually
	own_window_type = 'normal',				-- if own_window true options are: normal/override/dock/desktop/panel
	own_window_hints = 'undecorated,below,above,sticky,skip_taskbar,skip_pager',  -- if own_window true - just hints - own_window_type sets it

	--catppuccin
	color0 = '#C9CBFF',
	color1 = '#D9E0EE',
	color2 = '#89DCEB',
	color3 = '#F2CDCD',
	color4 = '#C3BAC6',
    color5 = '#ABE9B3',
    color6 = '#FAE3B0',
};

conky.text = [[
${font5}${color6}${color}${font}${offset 20}${color1}${font2}${color1}FILESYSTEM ${color2} ${hr 2}
${voffset 10}${color3}${font}|__Home: ${goto 100}${color1}${font}${fs_free /home} / ${color5}${fs_size /home} ${alignr}${color1}${fs_used_perc /home}%
${color3}${font}|__Entmt: ${goto 100}${color1}${font}${fs_free /mnt/entmt} / ${color5}${fs_size /mnt/entmt}${alignr}${color1}${fs_used_perc /mnt/entmt}%
${color3}${font}|__Data: ${goto 100}${color1}${font}${fs_free /mnt/data} / ${color5}${fs_size /mnt/data}${alignr}${color1}${fs_used_perc /mnt/data}%
${color3}${font}|__Movies: ${goto 100}${color1}${font} ${fs_free /mnt/movies} / ${color5}${fs_size /mnt/movies}${alignr}${color1}${fs_used_perc /mnt/movies}%
${voffset 20}${font5}${color6}${color}${font}${offset 20}${color1}${font2}EXTERNAL ${color2} ${hr 2}
${voffset 10}${color3}${font}|__Backup: ${goto 100}${color1}${font} ${fs_free /run/media/akya/backup} / ${color5}${fs_size /run/media/akya/backup}${alignr}${color1}${fs_used_perc /run/media/akya/backup}%
${color3}${font}|__Dump: ${goto 100}${color1}${font} ${fs_free /run/media/akya/dump} / ${color5}${fs_size /run/media/akya/dump}${alignr}${color1}${fs_used_perc /run/media/akya/dump}%]];
```

**Comment by jjgomera** [comment] 2024-05-23 14:46
Me too, it's like minimum_height and minimum_width are not used, my dirty fix is add empty line at end of conky.text section

Version: 1.21.1-1
SO: Debian testing

Update last days, over 1.20.2, where worked fine

**Comment by brndnmtthws** [comment] 2024-05-23 14:56
I think this is likely related to the geometry changes, so I'm hoping @Caellian knows what's going on here and we can get a quick fix.

**Comment by AngryPhantom** [comment] 2024-05-24 07:42
> I think this is likely related to the geometry changes

What about those 'bold' bars? Also related to geometry?

I've looked into possible missing packages (I thought I needed gperf installed or something) but didn't find anything.
On one machine I have normal bars, on another one - bold ones. That's strange.

**Comment by Caellian** [comment] 2024-05-25 11:42
Closing as duplicate of #1925.

**Closed by Caellian** 2024-05-25 11:42 UTC
Labels: bug, triage

**Comment by frankspace** [comment] 2024-05-26 01:45
I just upgraded from 1.19.6 to 1.21.1, and I'm also encountering this weird bug where suddenly a lot of lines are bolded.  I can fix the horizontal "`$hr`" lines by changing that to "`${hr (1)}", but I can't figure out how to unboldify the bars.  If that's a wontfix because it isn't considered a bug, than what is _the exact precise thing_ I need to do to de-boldify stuff back to the way it was before?

**Comment by Caellian** [comment] 2024-05-26 02:39
> If that's a wontfix because it isn't considered a bug, than what is _the exact precise thing_ I need to do to de-boldify stuff back to the way it was before?

It's closed because there's already two issues dedicated to separate parts of this issue that were created before this one. See last comment and linked issue, right before your message.
