### ISSUE TITLE
Any plan for wayland?

### ISSUE THREAD

**Issue by zhw2101024** [brndnmtthws/conky#56] opened 2014-07-15 15:38 UTC
Is it possible to add support for wayland?

**Comment by AquaL1te** [comment] 2017-03-31 09:48
Conky is the last one that needs to add support for Wayland on my desktop. The other one was Redshift, but GNOME created an alternative themselves with Wayland support. Please add Wayland support :)

**Comment by q2dg** [comment] 2017-07-13 20:18
Resolving this issue is crucial for Conky's future

**Comment by mmuman** [comment] 2017-11-27 21:46
Hi, I started a Conky port to Haiku #433 ... while we don't use Wayland, we don't use X11 either. So we also need the X11 code to be factored out to add proper Haiku GUI support.

This year Haiku is participating into the [Google Code-In](https://developers.google.com/open-source/gci/how-it-works) contest that is just starting, and Ubuntu is participating as well, and since they are now moving to Wayland, they might also be interested. If any dev is willing to help mentor the students, we could propose GCI tasks to clean up the code and add proper Wayland and Haiku support.

It would be the occasion to introduce some GUI platform base class and have the different implementations override it.

**Comment by CottonEaster** [comment] 2018-01-31 17:35
I too would very much like Wayland support in Conky.

**Comment by carlosgonzz** [comment] 2018-08-22 18:44
Any info on wayland support?

**Comment by npyl** [comment] 2018-09-08 10:04
Please checkout my issue in conky-for-macOS project: https://github.com/Conky-for-macOS/conky-for-macOS/issues/35 .  A similar problem has arisen for the macOS port:  there is need to ditch XLib and switch to modern APIs such as Metal.

**Comment by mmuman** [comment] 2018-09-09 14:48
So yeah, we should start by cleaning up and adding some platform base classes…

**Comment by npyl** [comment] 2018-09-09 14:54
@mmuman An idea is porting conky to wayland and then creating a translation layer between Wayland and Metal.  This way both macOS and Linux get supported **BUT** other OSes get left out, eg. BSDs.  I think Wayland doesn't run on BSD.

**Comment by mmuman** [comment] 2018-09-09 17:28
Using a toolkit would be an option but again, the usage pattern in conky is quite specific with desktop placement, and I don't think it's properly implemented in most toolkits.

**Comment by mmuman** [comment] 2018-09-11 12:43
I mean, putting an app's window on the desktop is a corner case that is probably not supported in most toolkits because it is usually very system-specific, and not used enough to require people to properly implement it.
At least I don't recall seeing a single toolkit mentioning it.

**Comment by mmuman** [comment] 2018-10-05 02:51
Ok, I had a try at cleaning up the mess. I already managed to decouple the HTTP stuff.

**Comment by mmuman** [comment] 2018-10-05 16:06
I think I almost got it for X11 in conky.cc except for the event loop, which is quite involved.

**Comment by mmuman** [comment] 2018-10-07 00:53
Btw, Haiku is again part of the Google Code-In contest, so if we get the X11 cleanup done we can have someone working on the Haiku port (if I don't do it myself in two nights first).
And possibly other ports under one of the [umbrella orgs](https://codein.withgoogle.com/organizations/). For example, the KDE projects could be interested in a Qt port (although it probably wouldn't be as integrated as possible, like displaying on the desktop).

**Comment by emersion** [comment] 2019-09-25 13:47
Wayland support for GNOME won't be possible. I think the way to go would be a GNOME Shell extension.

For other compositors, we have a standard called layer-shell. KDE doesn't implement it yet, but is interested in it. wlroots-based compositors and Mir support it. Feel free to ask us questions about porting to Wayland (you can join us in #sway-devel on Freenode).

**Comment by mmuman** [comment] 2019-09-25 14:27
Well, supporting GNOME will require some creativity, but not much more than to support Haiku, which will require Tracker (the file manager which handles the desktop) to load ourselves as an add-on (essentially dlopen() to call an instantiation function to return a BView object to add to the hierarchy of widgets on the desktop), and triggering this from the command line.

Because it used to work with X11 which allows any window from any process to be grafted on another one doesn't mean this can't be changed.

**Comment by emersion** [comment] 2019-09-25 16:47
Yeah sure, but it's more "GNOME support" than "Wayland support" :P

**Comment by kushraj** [comment] 2021-02-27 22:38
Is there anything about implementation of  layer-shell protocol ? conky mostly works in sway but can't be displayed as a background layer yet

**Comment by LinuxOnTheDesktop** [comment] 2021-04-25 09:45
Note: Wayland has replaced X as the default in Ubuntu 21.04. That version of Ubuntu was released on  22 April 2021. ([Here](https://ubuntu.com/blog/ubuntu-21-04-is-here) is the release announcement.)

**Comment by kushraj** [comment] 2021-09-29 09:13
Any hope for a proper implementation in sway for this ?

**Comment by mmuman** [comment] 2021-09-29 11:29
Well I still intend to get this work merged someday, but each time I look at it I have to rebase over and spend hours integrating changes that happened since then to avoid regressions, so it's not fun.

**Comment by Dungeonseeker** [comment] 2021-11-02 08:46
I can test, Currently having issues with conky showing off screen on wayland, is fine on X. At least I can see if that issue is fixed.

Will pull and build after I have walked my dog

**Comment by mmuman** [comment] 2021-11-02 09:20
Well since it's just the X11 code that's been moved around it won't be fixed, but it shouldn't introduce any regression.
I'll leave you to implement the Wayland backend then :-D

**Comment by tmpm697** [comment] 2022-07-10 06:58
any update on this?

**Comment by mmuman** [comment] 2022-07-10 09:19
Not really, I wanted to do some more cleanups on #664 but it should be mergeable already mostly. I didn't get many returns on it, anyone ever tried it?

**Comment by mmuman** [comment] 2022-09-14 16:35
Since #664 has been merged, we're not far from being able to support other GUI frameworks. There are still some strings attached to X11 here and there, like settings objects, that we should discuss how to handle. Do we want to fake them on other platforms, or do we want to have separate ones…

**Comment by npyl** [comment] 2022-09-15 07:47
I took a stub at starting a METAL port, and I realised that there are some variables like `out_to_x` for example that are still tied to X11 (as you said).

Some of them though, like `colours` seem platform neutral.  Maybe some should go in `display-output.hh`??

**Comment by mmuman** [comment] 2022-09-18 22:34
> Some of them though, like `colours` seem platform neutral. Maybe some should go in `display-output.hh`??

I was thinking those were too GUI-specific but they could also be used by ncurses, so why not.

**Comment by mmuman** [comment] 2022-10-09 20:59
I had a try at an SDL 1.2 backend (2.x is not available on older OSes). For now it opens a window. Still building with X11 too so it didn't need cleanup yet.

**Comment by mmuman** [comment] 2022-10-13 03:35
And we have some text…
![Screenshot_20221013_053333](https://user-images.githubusercontent.com/470143/195493177-452026ca-a6f9-467e-9b67-0fc5b330d30a.png)

**Comment by saltasatelites** [comment] 2022-12-27 13:03
Have you take a look to nwg-wrapper? Maybe could help; allows show text on the screen and show some text too.

**Comment by saltasatelites** [comment] 2022-12-27 17:27
Have you take a look to nwg-wrapper? Maybe could help, allows show in image on the screen and show some text too, but the developer has said he has no interest about conky.

**Comment by saltasatelites** [comment] 2023-01-04 13:51
Have you taken a look to nwg-wrapper? Maybe could help; allows show text on the screen and show image too. But the developer has said he has no interest to make a fork on conky to wayland...

**Comment by Iss-in** [comment] 2023-01-04 16:58
i would say eww is a much better replacement

**Comment by Soundtoxin** [comment] 2024-01-06 09:45
Bump.

**Comment by Galicarnax** [comment] 2024-02-25 04:10
I don't understand why the repo title now mentions Wayland, as if Conky is as usable in Wayland as in X now. I've spent some time now trying to get rid of XWayland and re-configure `conky` to use with pure Wayland (`swaywm`), but failed miserably. `${image ...}` does not work (Imlib2 complains about some NULL params), graphs are not drawn, even just using `${stippled_hr}` prevents further output. Was trying that with the latest `conky` version, for sure.

Please note, I'm not complaining that Wayland support is still poor. My point is that saying "for X, Wayland, and other things, too" in the title might be misleading. It's just too early for that. Or am I the only one with these kind of issues in Wayland?

**Comment by ben2talk** [comment] 2024-03-29 05:25
```
conky.config = {
-- Conky settings
	background = true,
	update_interval = 30,
	double_buffer = true,
	no_buffers = true,

-- Window specifications
	alignment = 'br',
	gap_x = 20,
	gap_y = 42,
	
	own_window = true,
	own_window_transparent = true,
	own_window_argb_visual = true,
	own_window_argb_value = 70,
	own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
	own_window_class = 'conky',

-- Text
	use_xft = true,
	xftalpha = 0.1,
	font = 'Arial Rounded MT bold :size=10',
	font = 'firacode nerd font :bold:size=9',

	draw_shades = true,
	default_color = '#666666',
};

conky.text = [[${fs_bar 5,55 /} Evo ${goto 100}${fs_free /}${if_match ${fs_used_perc}>=75}${color lightsalmon}${endif}${if_match ${fs_used_perc}>=85}${color red}${endif}$color
${if_existing /dev/sdd}${fs_bar 5,55 /mnt/T3}${font }${color } T3 ${goto 100}${fs_free /mnt/T3} ${if_match ${fs_used_perc /mnt/T3}>=85}${color salmon}${if_match ${fs_used_perc}>=85}${color red}${endif}${endif}$color
${if_existing /dev/sdc}${fs_bar 5,55 /mnt/T4}${font }${color } T4 ${goto 100}${fs_free /mnt/T4} ${if_match ${fs_used_perc /mnt/T4}>=85}${color salmon}${endif}${if_match ${fs_used_perc}>=95}${color red}${endif}$color
${if_existing /dev/sdd}${fs_bar 5,55 /mnt/W2}${font }${color } W2 ${goto 100}${fs_free /mnt/W2} ${if_match ${fs_used_perc /mnt/W2}>=85}${color salmon}${endif}${if_match ${fs_used_perc}>=95}${color red}${endif}$color]];

```
If set for Wayland, the GoTo's and 'Align' lines are broken.
If set for X, now on Plasma 6, then Conky windows are presented as windows in Overview and Grid.

Is there any future here? Or is Conky the last (and ONLY) existing app of it's kind?

**Comment by brndnmtthws** [comment] 2024-03-29 11:41
> Please note, I'm not complaining that Wayland support is still poor. My point is that saying "for X, Wayland, and other things, too" in the title might be misleading. It's just too early for that. Or am I the only one with these kind of issues in Wayland?

This is fair. I updated the description accordingly:

<img width="357" alt="Screenshot 2024-03-29 at 07 37 09" src="https://github.com/brndnmtthws/conky/assets/3129093/3b3d4e21-1759-49b8-8dac-b621ec10ef8a">

And the README in #1790.

The reality is that it's very hard to support all the different things while not breaking existing functionality. I personally have to focus my life energy on doing things that allow me to pay rent and buy food, and it's quite time consuming to debug these issues.

I should also mention that I really appreciate all the help and contributions from everyone with this project, and I know that it has its deficiencies, but at the very least I will never use it as a way to extract money from people.

**Comment by Caellian** [comment] 2024-04-19 15:24
I created a [milestone for Wayland](https://github.com/brndnmtthws/conky/milestone/1).

Basic support is here thanks to previous contributors, there's a lot of work ahead, but I'm closing this issue as resolved because _any support_ exists, this issue is quite old, and pinging all 17 participants for followup questions might not be the best idea.

Future wanderers, take a look at the [milestone](https://github.com/brndnmtthws/conky/milestone/1) to check if your specific issue is already tracked or create a new one.

**Closed by Caellian** 2024-04-19 15:24 UTC
Labels: enhancement, display: wayland, priority: high

**Comment by Dreamsorcerer** [comment] 2024-04-19 16:13
For those installing through downstream packages, from which version is Wayland supported in?

**Comment by Dreamsorcerer** [comment] 2024-04-19 16:28
Looking through the wiki, I've just seen that this won't work with GNOME yet, so probably doesn't matter to me.
I'd note that the link in the wiki is labelled as 'WON'T FIX' (https://github.com/brndnmtthws/conky/wiki/Window-Configuration#wayland), but reading the details it appears that they are expecting GNOME Shell to implement the extension instead of Mutter, so it may work in future (appears something was merged last week as the first step to this being possible).

**Comment by Caellian** [comment] 2024-04-19 17:02
@Dreamsorcerer I can't find a single issue where they said anything other than:
> [No there is not, we don't intend to support third party panels, lock screens, notification UI's etc.](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/1141)

Such a thing could be implemented by either Mutter or GNOME Shell. But they've been asked about this A LOT and they consistently answer that they don't support 3rd party widgets and that such things need to be implemented through their plugin system. If you don't want a Windows-esque interface, don't use GNOME. If support gets added, it will work with conky without any modifications. If some other layer protocol gets added suggested, we can (probably) easily support it as well.
