### ISSUE TITLE
[Bug]: v1.20_2 conky: can't parse hex color 'white' (5)

### ISSUE THREAD

**Issue by infoslaw** [brndnmtthws/conky#1904] opened 2024-05-11 10:15 UTC
### What happened?

after upgrade to v1.20_2 conky can't parse hex color 'white' (5) or other colors
all default in red colors

### Version

1.20.2

### Which OS/distro are you seeing the problem on?

Arch Linux

### Conky config

```Lua
conky.config = {
-- ARCH-CONKY


-- Enable real transparency (KDE4)
	own_window = true,
	own_window_transparent = true,
	own_window_argb_visual = true,
	own_window_type = 'normal',--values are: 'normal', 'dock', 'panel', 'desktop', 'override'
	own_window_class = 'conky-semi',
	own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',

-- Create own window instead of using desktop (required in nautilus)
-- own_window yes
-- own_window_type override
-- own_window_transparent yes
-- own_window_hints undecorated,below,sticky,skip_taskbar,skip_pager

-- Env manager
-- out_to_wayland = true
-- out_to_x = false

-- Use double buffering (reduces flicker, may not work for everyone)
	double_buffer = true,

-- fiddle with window
	use_spacer = 'right',
	use_xft = true,

-- Update interval in seconds
	update_interval = 3.0,

-- Minimum size of text area
	minimum_width = 200, minimum_height = 500,

-- Draw shades?
	draw_shades = false,

-- Text stuff
	draw_outline = false,-- amplifies text if yes
	draw_borders = false,
-- font Arial
	font = 'DejaVu Sans',
	uppercase = false,-- set to yes if you want all text to be in uppercase

-- Stippled borders?
	stippled_borders = 3,

-- border width
	border_width = 10,

-- Default colors and also border colors, grey90 == #e5e5e5
	default_color = 'white',
-- grey

-- own_window_colour = 'brown',

-- Text alignment, other possible values are commented
--alignment top_left
	alignment = 'top_right',
--alignment bottom_left
--alignment bottom_right

-- Gap between borders of screen and text
	gap_x = 10,
	gap_y = 10,

-- number of cpu samples to average
-- set to 1 to disable averaging
	cpu_avg_samples = 2,

	text_buffer_size = 1024,

-- stuff after âTEXTâ will be formatted on screen

};

conky.text = [[
$color${font DejaVu Sans:size=7}
$nodename@$sysname $kernel on $machine${font DejaVu Sans Book:size=7}
${color}Uptime: $uptime ${color #0077ff}

${color orange}BATTERY $color
${execi 60 acpi -b | awk '{print$5}'} ${alignr} (${execi 60 acpi -b | awk '{print $4}' | cut -b -3})
${battery_bar BAT0}

${color orange}CPU $color
${freq}MHz${alignr}Load: ${loadavg}
${alignr}${loadgraph 20,250 e5e5e5 F1AA0E}
CPU Total:${color} ${cpu cpu0}% ${color}${alignr}Temp:${color} ${acpitemp}
#${alignr}${cpugraph 0 20,250 e5e5e5 F1AA0E}

CPU0: ${color}${cpu cpu0}% ${alignr} CPU1: ${color}${cpu cpu1}%
${cpugraph 0 10,120 e5e5e5 F1AA0E}${alignr}${cpugraph 1 10,120 e5e5e5 F1AA0E}

CPU2: ${color}${cpu cpu2}% ${alignr} CPU3: ${color}${cpu cpu3}%
${cpugraph 2 10,120 e5e5e5 F1AA0E}${alignr}${cpugraph 3 10,120 e5e5e5 F1AA0E}

CPU4: ${color}${cpu cpu4}% ${alignr} CPU5: ${color}${cpu cpu5}%
${cpugraph 2 10,120 e5e5e5 F1AA0E}${alignr}${cpugraph 3 10,120 e5e5e5 F1AA0E}

CPU6: ${color}${cpu cpu6}% ${alignr} CPU7: ${color}${cpu cpu7}%
${cpugraph 2 10,120 e5e5e5 F1AA0E}${alignr}${cpugraph 3 10,120 e5e5e5 F1AA0E}

NAME                         ${alignr}PID       ${alignr}CPU%         ${alignr}MEM%
${top name 1}      ${alignr} ${top pid 1}       ${top cpu 1}          ${top mem 1}
${top name 2}      ${alignr} ${top pid 2}       ${top cpu 2}          ${top mem 2}
${top name 3}      ${alignr} ${top pid 3}       ${top cpu 3}          ${top mem 3}
${top name 4}      ${alignr} ${top pid 4}       ${top cpu 4}          ${top mem 4}

${color orange}MEMORY / DISK $color
Total: ${color}${memmax} ${alignr} Free: ${color}${memfree}
RAM: $memperc% ${alignr}Swap: $swapperc% 
${memgraph 20,120 e5e5e5 F1AA0E} ${alignr} ${swapbar 20,120 }
root: ${fs_used_perc /}% ${fs_bar 6 /}$color
home: ${fs_used_perc /home/slav}% ${fs_bar 6 /home/slav}$color

#${color orange}LAN DOCK [${addr enp0s20f0u2u1u3}] $color
#Down: $color${downspeed enp0s20f0u2u1u3} k/s ${alignr}Up: ${upspeed enp0s20f0u2u1u3} k/s
#${downspeedgraph enp0s20f0u2u1u3 20,120 000000 ff0000} ${alignr}${upspeedgraph enp0s20f0u2u1u3
#20,120 e5e5e5 F1AA0E}$color
#Total: ${totaldown enp0s20f0u2u1u3} ${alignr}Total: ${totalup enp0s20f0u2u1u3}
#enp0s20f0u2u1u3

${color orange}LAN DOCK [${addr enp0s31f6}] $color
Down: $color${downspeed enp0s31f6} k/s ${alignr}Up: ${upspeed enp0s31f6} k/s
${downspeedgraph enp0s31f6 20,120 000000 ff0000} ${alignr}${upspeedgraph enp0s31f6
20,120 e5e5e5 F1AA0E}$color
Total: ${totaldown enp0s31f6} ${alignr}Total: ${totalup enp0s31f6}

# LAN USBC 1 LAPTOP #
${color orange}LAN USB [${addr enp58s0u1}] $color
Down: $color${downspeed enp58s0u1} k/s ${alignr}Up: ${upspeed enp58s0u1} k/s
${downspeedgraph enp58s0u1 20,120 000000 ff0000} ${alignr}${upspeedgraph enp58s0u1
20,120 e5e5e5 F1AA0E}$color
Total: ${totaldown enp58s0u1} ${alignr}Total: ${totalup enp58s0u1}

# LAN USBC 2 LAPTOP #
# ${color orange}LAN USBC 2 [${addr enp0s20f0u2}] $color
# Down: $color${downspeed enp0s20f0u2} k/s ${alignr}Up: ${upspeed enp0s20f0u2} k/s
# ${downspeedgraph enp0s20f0u2 20,120 000000 ff0000} ${alignr}${upspeedgraph enp0s20f0u2
# 20,120 e5e5e5 F1AA0E}$color
# Total: ${totaldown enp0s20f0u2} ${alignr}Total: ${totalup enp0s20f0u2}

${color orange}WLAN [${addr wlp0s20f3}] $color
${wireless_essid wlp0s20f3} ${wireless_link_bar 6 wlp0s20f3}
Down: $color${downspeed wlp0s20f3} k/s ${alignr}Up: ${upspeed wlp0s20f3} k/s
${downspeedgraph wlp0s20f3 20,120 e5e5e5 F1AA0E} ${alignr}${upspeedgraph wlp0s20f3
20,120 e5e5e5 F1AA0E}$color
Total: ${totaldown wlp0s20f3} ${alignr}Total: ${totalup wlp0s20f3}
Inbound: ${tcp_portmon 1 32767 count} Outbound: ${tcp_portmon 32768
61000 count}${alignr}Total: ${tcp_portmon 1 65535 count}

${color orange}WWAN [${addr wwp0s20f0u7}] $color
Down: $color${downspeed wwp0s20f0u7} k/s ${alignr}Up: ${upspeed wwp0s20f0u7} k/s
${downspeedgraph wwp0s20f0u7 20,120 e5e5e5 F1AA0E} ${alignr}${upspeedgraph wwp0s20f0u7
20,120 e5e5e5 F1AA0E}$color
Total: ${totaldown wwp0s20f0u7} ${alignr}Total: ${totalup wwp0s20f0u7}
Inbound: ${tcp_portmon 1 32767 count} Outbound: ${tcp_portmon 32768
61000 count}${alignr}Total: ${tcp_portmon 1 65535 count}
]];
```

### Relevant log output

```Shell
conky: can't parse hex color '10,120' (6)
conky: can't parse hex color '3' (1)
conky: can't parse hex color '10,120' (6)
conky: can't parse hex color 'orange' (6)
conky: can't parse hex color 'white' (5)
conky: can't parse hex color 'white' (5)
conky: can't parse hex color 'white' (5)
conky: can't parse hex color 'white' (5)
conky: can't parse hex color 'white' (5)
conky: can't parse hex color 'orange' (6)
conky: can't parse hex color 'white' (5)
conky: can't parse hex color 'white' (5)
conky: can't parse hex color 'white' (5)
conky: can't parse hex color 'orange' (6)
conky: can't parse hex color 'white' (5)
conky: can't parse hex color 'white' (5)
conky: can't parse hex color 'white' (5)
conky: can't parse hex color 'orange' (6)
conky: can't parse hex color 'white' (5)
conky: can't parse hex color 'white' (5)
conky: can't parse hex color 'white' (5)
conky: can't parse hex color 'orange' (6)
conky: can't parse hex color 'white' (5)
conky: can't parse hex color 'white' (5)
conky: can't parse hex color 'white' (5)
conky: FOUND: console
conky: FOUND: ncurses
conky: FOUND: file
conky: FOUND: x11
conky: FOUND: wayland
conky: can't parse hex color 'white' (5)
conky: '(null)' wayland session running 'KDE' destop
conky: can't parse hex color 'white' (5)
conky: can't parse hex color 'white' (5)
conky: can't parse hex color 'white' (5)
conky: can't parse hex color 'white' (5)
qconky: can't parse hex color 'white' (5)
```

**Comment by infoslaw** [comment] 2024-05-11 10:41
temporary solution to change color name for hex format
f.e.
${color #ecb939}BATTERY $color

**Comment by andreymal** [comment] 2024-05-11 10:47
Duplicate of https://github.com/brndnmtthws/conky/issues/1868

This is an Arch packaging bug: https://gitlab.archlinux.org/archlinux/packaging/packages/conky/-/issues/5

**Comment by infoslaw** [comment] 2024-05-11 10:52
Yes I read about it however haven't before gperf.
Anyway found workaround by put everywhere in .conkyrc hex codes instead names.
Thank you.

**Comment by AngryPhantom** [comment] 2024-05-11 11:49
I can confirm this. Not only 'white' but _any color_. The fix is to use hex codes.

Also, I would like to kindly ask the dev to make config a bit more uniform:

own_window_colour
default_outline_color

Make it either **color** or **colour** everywhere. Or make it _interchangeable_.

It distracts a lot, simply because putting color (or colour) everywhere doesn't work. You have to remember every option or consult the docs every time.

Thanks in advance.

**Comment by Caellian** [comment] 2024-05-11 17:06
> Anyway found workaround by put everywhere in .conkyrc hex codes instead names.

Or `pacman -Sy gperf` during build if you're building an older version from AUR. New builds will fail instead of producing warnings with `-D` at runtime and there's an option to revert to that behavior (in case someone isn't using color names) though build configuration.

Sorry for inconvenience with packaging :face_with_diagonal_mouth:. On a flip side, you can now easily add/change parsed colors in [`data/color-names.yml`](https://github.com/brndnmtthws/conky/blob/6bf383cf786a9615480b0268571cb2ad84e2fd24/data/color-names.yml) as their parsing is no longer hardcoded and uses a tiny bit faster algorithm.

Closing as duplicate of #1868.

**Closed by Caellian** 2024-05-11 17:06 UTC
Labels: bug, triage

**Comment by Atreyagaurav** [comment] 2024-05-19 04:45
Hi guys. I saw that the problem is from not having a dependency and fixable by using HEX. But I feel like this showed an important default (using color red when color couldn't be parsed) that should be changed.

In my opinion, using white color would make a lot more sense as a default than red color when something like this happens.

**Comment by fvalenduc** [comment] 2024-10-06 15:55
I have gentoo and gperf is installed. However I still have to use hex codes.

**Comment by Caellian** [comment] 2024-10-06 16:53
> I have gentoo and gperf is installed. However I still have to use hex codes.

See my [reply on the other issue](https://github.com/brndnmtthws/conky/issues/1868#issuecomment-2395506095).
